import { NextResponse } from "next/server";
import type { BudgetCeilingPolicyService, PublishBudgetCeilingPolicyInput } from "@/application/budget-ceiling-policy-service";
import { BudgetCeilingPolicyServiceError } from "@/application/budget-ceiling-policy-service";
import { BudgetCeilingPolicyRepositoryError } from "@/connectors/budget/budget-ceiling-policy-drizzle-repository";
import { can, type WorkspaceRole } from "@/security/authorization";
import type { TrustedDecisionRoomPrincipal } from "@/application/decision-room-agent-contract";

const HEADERS=Object.freeze({"Cache-Control":"private, no-store, max-age=0","X-Content-Type-Options":"nosniff","X-ReklamZeka-Access-Mode":"published-budget-constraint-only","X-ReklamZeka-Action-Authority":"none","X-ReklamZeka-Meta-Write":"disabled"});
const AUTHORITY=Object.freeze({canPublishConstraint:true as const,canApprove:false as const,canExecute:false as const,canWriteMeta:false as const});
const error=(code:string,message:string,status:number)=>NextResponse.json({error:{code,message},authority:{...AUTHORITY,canPublishConstraint:false}},{status,headers:HEADERS});
function exact(value:unknown,keys:readonly string[]):asserts value is Record<string,unknown>{if(!value||typeof value!=="object"||Array.isArray(value)||Object.keys(value).length!==keys.length||Object.keys(value).some((key)=>!keys.includes(key)))throw new BudgetCeilingPolicyServiceError("invalid_input");}
async function command(request:Request){const raw=await request.text();if(Buffer.byteLength(raw)>32_000)throw new BudgetCeilingPolicyServiceError("invalid_input");const value=JSON.parse(raw) as unknown;exact(value,["command"]);exact(value.command,["limitRef","revision","previousPolicyHash","poolRef","parentLimitRef","layer","targetScopeRef","market","currency","ceilingDecimal","effectiveFrom","effectiveTo","state"]);return value.command as unknown as Omit<PublishBudgetCeilingPolicyInput,"workspaceId">;}
function shape(request:Request){const url=new URL(request.url),origin=request.headers.get("origin");if(request.method!=="POST"||url.search||request.headers.has("authorization")||!request.headers.get("cookie")||request.headers.get("sec-fetch-site")!=="same-origin"||request.headers.get("x-reklamzeka-intent")!=="budget-ceiling-policy-publish"||request.headers.get("content-type")?.toLowerCase()!=="application/json"||!origin||new URL(origin).origin!==url.origin)throw new BudgetCeilingPolicyServiceError("invalid_input");}
function failure(reason:unknown){if(reason instanceof BudgetCeilingPolicyRepositoryError){if(["scope_denied","role_denied"].includes(reason.code))return error("forbidden","Bu ceiling politikasını yayımlama yetkiniz yok.",403);if(reason.code==="revision_conflict")return error("conflict","Ceiling politikası siz çalışırken değişti.",409);}if(reason instanceof BudgetCeilingPolicyServiceError||reason instanceof SyntaxError)return error("invalid_input","Ceiling policy isteği geçersiz.",400);return error("unavailable","Ceiling policy kayıt defteri kullanılamıyor.",503);}
export const budgetCeilingPolicyNotConfiguredResponse=()=>error("source_not_configured","Ceiling policy kaynağı bağlı değil.",503);
export const budgetCeilingPolicySessionRequiredResponse=()=>error("local_session_required","Ceiling policy için yerel oturumu bağlayın.",401);
export function createBudgetCeilingPolicyHttpHandler(input:Readonly<{service:Pick<BudgetCeilingPolicyService,"publish">;resolveActor(request:Request):Promise<Readonly<{principal:TrustedDecisionRoomPrincipal;role:WorkspaceRole}>>}>){return async(request:Request)=>{try{shape(request);const actor=await input.resolveActor(request);if(!can(actor.role,"instruction_policy:publish"))return error("forbidden","Yalnız owner/admin ceiling politikası yayımlayabilir.",403);const result=await input.service.publish(actor.principal.actor.userId,{workspaceId:actor.principal.workspaceId,...await command(request)});return NextResponse.json({contractVersion:"budget-ceiling-policy-http/1.0.0",item:result.policy,persistence:result.persistence,auditAppended:result.auditAppended,authority:AUTHORITY},{status:result.persistence==="inserted"?201:200,headers:HEADERS});}catch(reason){return failure(reason);}};}
