import { NextResponse } from "next/server";
import type { TrustedDecisionRoomPrincipal } from "@/application/decision-room-agent-contract";
import type { CampaignClassificationReviewService } from "@/application/campaign-classification-review-service";
import { AuthorizationError } from "@/security/authorization";
const headers = Object.freeze({ "Cache-Control": "private, no-store, max-age=0", "X-Content-Type-Options": "nosniff", "X-ReklamZeka-Access-Mode": "classification-review-read", "X-ReklamZeka-Action-Authority": "none", "X-ReklamZeka-Meta-Network": "disabled" });
const authority = Object.freeze({ canAssign: false, canPublish: false, canAuthorizeAction: false, canWriteMeta: false });
const fail = (status: number, code: string, message: string) => NextResponse.json({ error: { code, message }, authority }, { status, headers });
export const campaignClassificationReviewNotConfiguredResponse = () => fail(503, "source_not_configured", "Kampanya künye inceleme kaynağı yerel çalışma alanına henüz bağlanmadı.");
export const campaignClassificationReviewSessionRequiredResponse = () => fail(401, "local_session_required", "Kampanya künye incelemesi için yerel dashboard oturumunu bağlayın.");
export function createCampaignClassificationReviewHttpHandler(input: Readonly<{ service: Pick<CampaignClassificationReviewService, "list">; resolvePrincipal(request: Request): Promise<TrustedDecisionRoomPrincipal | null> }>) { return async (request: Request) => { try { const url = new URL(request.url); if (request.method !== "GET" || url.search || request.headers.has("authorization") || !request.headers.get("cookie") || request.headers.has("x-workspace-id") || request.headers.has("x-workspace-ref") || request.headers.get("sec-fetch-site") !== "same-origin" || request.headers.get("x-reklamzeka-intent") !== "campaign-classification-review-read") return fail(400, "invalid_input", "Kampanya künye inceleme isteği geçersiz."); const principal = await input.resolvePrincipal(request); if (!principal) throw new AuthorizationError(); return NextResponse.json(await input.service.list(principal), { headers }); } catch (reason) { if (reason instanceof AuthorizationError) return fail(403, "forbidden", reason.publicMessage); return campaignClassificationReviewNotConfiguredResponse(); } }; }
