import type { NodePgDatabase } from "drizzle-orm/node-postgres";
import { SliceRuleBudgetPoolBindingService } from "@/application/slice-rule-budget-pool-binding-service";
import { DrizzleBudgetPoolHierarchyRepository } from "@/connectors/budget/budget-pool-hierarchy-drizzle-repository";
import { DrizzleSliceRuleBudgetPoolBindingRepository } from "@/connectors/campaigns/slice-rule-budget-pool-binding-drizzle-repository";
import * as schema from "@/db/schema";
import { LocalDecisionRoomBoundaryError, resolveTrustedLocalInstructionPolicyPrincipal, type LocalDecisionRoomConfig } from "@/server/local-decision-room-runtime";
import { createSliceRuleBudgetPoolBindingHttpHandlers, sliceRuleBudgetPoolBindingNotConfiguredResponse, sliceRuleBudgetPoolBindingSessionRequiredResponse } from "@/server/slice-rule-budget-pool-binding-http";
import { LocalSessionCapabilityError } from "@/security/local-session-capability";
type Database = NodePgDatabase<typeof schema>;
export function createLocalSliceRuleBudgetPoolBindingHandlers(input: Readonly<{ database: Pick<Database, "select" | "insert" | "execute" | "transaction">; config: LocalDecisionRoomConfig; now?: () => string }>) { const invoke = async (request: Request, operation: "read" | "draft") => { try { const bound = await resolveTrustedLocalInstructionPolicyPrincipal({ request, database: input.database, config: input.config, requiredScope: operation === "read" ? "instruction_policy:read" : "instruction_policy:draft" }); const repository = new DrizzleSliceRuleBudgetPoolBindingRepository(input.database as never); const handlers = createSliceRuleBudgetPoolBindingHttpHandlers({ repository, bindingService: new SliceRuleBudgetPoolBindingService(repository), hierarchyRepository: new DrizzleBudgetPoolHierarchyRepository(input.database as never), resolveActor: async () => ({ principal: bound.principal, role: bound.membership.role }), now: input.now ?? (() => new Date().toISOString()) }); return operation === "read" ? handlers.GET(request) : handlers.POST(request); } catch (reason) { return reason instanceof LocalDecisionRoomBoundaryError || reason instanceof LocalSessionCapabilityError ? sliceRuleBudgetPoolBindingSessionRequiredResponse() : sliceRuleBudgetPoolBindingNotConfiguredResponse(); } }; return Object.freeze({ GET: (request: Request) => invoke(request, "read"), POST: (request: Request) => invoke(request, "draft") }); }
