import { NextResponse } from "next/server";

import { SliceRuleBudgetPoolBindingService, type SliceRuleBudgetPoolBinding } from "@/application/slice-rule-budget-pool-binding-service";
import type { BudgetPoolHierarchyRevision } from "@/application/budget-pool-hierarchy-service";
import type { TrustedDecisionRoomPrincipal } from "@/application/decision-room-agent-contract";
import { SliceRuleBudgetPoolBindingRepositoryError, type DrizzleSliceRuleBudgetPoolBindingRepository } from "@/connectors/campaigns/slice-rule-budget-pool-binding-drizzle-repository";
import type { DrizzleBudgetPoolHierarchyRepository } from "@/connectors/budget/budget-pool-hierarchy-drizzle-repository";
import { can, type WorkspaceRole } from "@/security/authorization";

const HEADERS = Object.freeze({ "Cache-Control": "private, no-store, max-age=0", "X-Content-Type-Options": "nosniff", "X-ReklamZeka-Access-Mode": "slice-rule-budget-pool-binding", "X-ReklamZeka-Action-Authority": "none", "X-ReklamZeka-Meta-Write": "disabled" });
const CLOSED = Object.freeze({ canPublish: false as const, canApprove: false as const, canExecute: false as const, canWriteMeta: false as const, canEnableAutomation: false as const });
type Actor = Readonly<{ principal: TrustedDecisionRoomPrincipal; role: WorkspaceRole }>;
type Command = Readonly<{ draftHash: string; hierarchyHash: string; poolRef: string; market: "domestic" | "international"; idempotencyKey: string }>;
const HASH = /^[a-f0-9]{64}$/; const REF = /^[a-z][a-z0-9_.:-]{0,127}$/;
function fail(code: string, message: string, status: number) { return NextResponse.json({ error: { code, message }, authority: CLOSED }, { status, headers: HEADERS }); }
function exact(value: unknown, keys: readonly string[]): asserts value is Record<string, unknown> { if (!value || typeof value !== "object" || Array.isArray(value) || Object.keys(value).length !== keys.length || Object.keys(value).some((key) => !keys.includes(key))) throw new Error("invalid_input"); }
function shape(request: Request, method: "GET" | "POST", intent: string) { const url = new URL(request.url); const origin = request.headers.get("origin"); if (request.method !== method || url.search || request.headers.has("authorization") || !request.headers.get("cookie") || request.headers.has("x-workspace-id") || request.headers.get("sec-fetch-site") !== "same-origin" || request.headers.get("x-reklamzeka-intent") !== intent || method === "POST" && (!origin || new URL(origin).origin !== url.origin || request.headers.get("content-type")?.toLowerCase() !== "application/json")) throw new Error("invalid_input"); }
async function command(request: Request): Promise<Command> { const raw = await request.text(); if (Buffer.byteLength(raw) > 2_000) throw new Error("invalid_input"); const parsed = JSON.parse(raw) as unknown; exact(parsed, ["command"]); exact(parsed.command, ["draftHash", "hierarchyHash", "poolRef", "market", "idempotencyKey"]); const value = parsed.command as Command; if (!HASH.test(value.draftHash) || !HASH.test(value.hierarchyHash) || !/^budget_pool_[a-z0-9][a-z0-9_.:-]{0,119}$/.test(value.poolRef) || !REF.test(value.idempotencyKey) || !["domestic", "international"].includes(value.market)) throw new Error("invalid_input"); return value; }
function publicHierarchy(revision: BudgetPoolHierarchyRevision | null) { return revision === null ? null : Object.freeze({ hierarchyHash: revision.hierarchy.hierarchyHash, nodes: revision.hierarchy.nodes.map((node) => Object.freeze({ poolRef: node.poolRef, parentPoolRef: node.parentPoolRef, layer: node.layer, market: node.market, currency: node.currency, hardCapDecimal: node.hardCapDecimal, effectiveFrom: node.effectiveFrom, effectiveTo: node.effectiveTo })), authority: CLOSED }); }
function failure(reason: unknown) { if (reason instanceof SliceRuleBudgetPoolBindingRepositoryError) { if (["market_mismatch", "draft_missing", "pool_missing"].includes(reason.code)) return fail(reason.code, "Kural taslağı ile seçilen bütçe havuzu aynı immutable kapsamda doğrulanamadı.", 409); if (reason.code === "conflict") return fail("binding_exists", "Bu immutable taslak zaten başka bir bütçe havuzuna bağlanmış.", 409); } return fail("unavailable", "Bütçe havuzu bağlama kaydı güvenli biçimde tamamlanamadı.", 503); }
export function sliceRuleBudgetPoolBindingNotConfiguredResponse() { return fail("source_not_configured", "Bütçe havuzu bağlama kaynağı yerel oturuma bağlı değil.", 503); }
export function sliceRuleBudgetPoolBindingSessionRequiredResponse() { return fail("local_session_required", "Bütçe havuzu bağlamak için yerel dashboard oturumunu bağlayın.", 401); }
export function createSliceRuleBudgetPoolBindingHttpHandlers(input: Readonly<{ repository: Pick<DrizzleSliceRuleBudgetPoolBindingRepository, "list">; bindingService: Pick<SliceRuleBudgetPoolBindingService, "bind">; hierarchyRepository: Pick<DrizzleBudgetPoolHierarchyRepository, "loadCurrent">; resolveActor(request: Request, operation: "read" | "draft"): Promise<Actor>; now(): string }>) {
  return Object.freeze({
    GET: async (request: Request) => { try { shape(request, "GET", "slice-rule-budget-pool-binding-read"); const actor = await input.resolveActor(request, "read"); const [bindings, hierarchy] = await Promise.all([input.repository.list({ workspaceId: actor.principal.workspaceId, actorId: actor.principal.actor.userId }), input.hierarchyRepository.loadCurrent({ workspaceId: actor.principal.workspaceId, actorId: actor.principal.actor.userId })]); return NextResponse.json({ contractVersion: "slice-rule-budget-pool-binding-http/1.0.0", bindings, hierarchy: publicHierarchy(hierarchy), authority: { canRead: true, canBind: can(actor.role, "budget:draft"), ...CLOSED } }, { headers: HEADERS }); } catch (reason) { return failure(reason); } },
    POST: async (request: Request) => { try { shape(request, "POST", "slice-rule-budget-pool-binding-save"); const actor = await input.resolveActor(request, "draft"); if (!can(actor.role, "budget:draft")) return fail("forbidden", "Viewer rolü bütçe havuzu bağlayamaz.", 403); const parsed = await command(request); const result = await input.bindingService.bind(actor.principal.actor.userId, { workspaceId: actor.principal.workspaceId, ...parsed, boundAt: input.now() } satisfies Omit<SliceRuleBudgetPoolBinding, "authority">); return NextResponse.json({ contractVersion: "slice-rule-budget-pool-binding-save/1.0.0", draftHash: parsed.draftHash, hierarchyHash: parsed.hierarchyHash, poolRef: parsed.poolRef, market: parsed.market, persistence: result.outcome, authority: { canRead: true, canBind: true, ...CLOSED } }, { status: result.outcome === "inserted" ? 201 : 200, headers: HEADERS }); } catch (reason) { if (reason instanceof Error && reason.message === "invalid_input") return fail("invalid_input", "Bütçe havuzu bağlama isteği geçersiz.", 400); return failure(reason); } },
  });
}
