ALTER TABLE "orchestrator_conversation_turns" DROP CONSTRAINT "orchestrator_conversation_turns_skill_catalog_binding";--> statement-breakpoint
ALTER TABLE "orchestrator_interview_kit_revisions" DROP CONSTRAINT "orchestrator_interview_kit_revisions_source_snapshot";--> statement-breakpoint
ALTER TABLE "orchestrator_conversation_turns" ADD COLUMN "interview_kit_snapshots" jsonb DEFAULT '[]'::jsonb NOT NULL;--> statement-breakpoint
ALTER TABLE "orchestrator_conversation_turns" ADD COLUMN "interview_kit_binding_hash" text DEFAULT 'LEGACY_NOT_RECORDED' NOT NULL;--> statement-breakpoint
ALTER TABLE "orchestrator_conversation_turns" ADD CONSTRAINT "orchestrator_conversation_turns_skill_catalog_binding" CHECK (
    ("orchestrator_conversation_turns"."skill_catalog_binding_hash" = 'LEGACY_NOT_RECORDED' and "orchestrator_conversation_turns"."profile_snapshot" = '{"version":"legacy_not_recorded"}'::jsonb and "orchestrator_conversation_turns"."manifest_snapshots" = '[]'::jsonb and "orchestrator_conversation_turns"."playbook_snapshots" = '[]'::jsonb and "orchestrator_conversation_turns"."interview_kit_snapshots" = '[]'::jsonb and "orchestrator_conversation_turns"."interview_kit_binding_hash"='LEGACY_NOT_RECORDED')
    or ("orchestrator_conversation_turns"."skill_catalog_binding_hash" = 'UNAVAILABLE_NOT_BOUND' and "orchestrator_conversation_turns"."profile_snapshot" = '{"version":"unavailable_not_bound"}'::jsonb and "orchestrator_conversation_turns"."manifest_snapshots" = '[]'::jsonb and "orchestrator_conversation_turns"."playbook_snapshots" = '[]'::jsonb and "orchestrator_conversation_turns"."interview_kit_snapshots" = '[]'::jsonb and "orchestrator_conversation_turns"."interview_kit_binding_hash"='UNAVAILABLE_NOT_BOUND')
    or ("orchestrator_conversation_turns"."skill_catalog_binding_hash" ~ '^[a-f0-9]{64}$'
      and jsonb_typeof("orchestrator_conversation_turns"."profile_snapshot") = 'object'
      and "orchestrator_conversation_turns"."profile_snapshot" ?& array['version', 'profileRef', 'revision', 'profileHash']
      and "orchestrator_conversation_turns"."profile_snapshot" - array['version', 'profileRef', 'revision', 'profileHash'] = '{}'::jsonb
      and jsonb_typeof("orchestrator_conversation_turns"."manifest_snapshots") = 'array' and jsonb_array_length("orchestrator_conversation_turns"."manifest_snapshots") between 1 and 9
      and jsonb_typeof("orchestrator_conversation_turns"."playbook_snapshots") = 'array' and jsonb_array_length("orchestrator_conversation_turns"."playbook_snapshots") between 0 and 12
      and "orchestrator_conversation_turns"."interview_kit_binding_hash" ~ '^[a-f0-9]{64}$' and jsonb_typeof("orchestrator_conversation_turns"."interview_kit_snapshots")='array' and jsonb_array_length("orchestrator_conversation_turns"."interview_kit_snapshots") between 0 and 12
      and "orchestrator_conversation_turns"."playbook_snapshots"::text !~* '"(body|content|prompt|token|secret|authorization)"[[:space:]]*:')
  );--> statement-breakpoint
ALTER TABLE "orchestrator_interview_kit_revisions" ADD CONSTRAINT "orchestrator_interview_kit_revisions_source_snapshot" CHECK (jsonb_typeof("orchestrator_interview_kit_revisions"."source_snapshot") = 'object' and "orchestrator_interview_kit_revisions"."source_snapshot" ?& array['optionId','title','url','version','recordHash','reviewBy'] and "orchestrator_interview_kit_revisions"."source_snapshot" - array['optionId','title','url','version','recordHash','reviewBy'] = '{}'::jsonb and "orchestrator_interview_kit_revisions"."source_snapshot"->>'recordHash' ~ '^[a-f0-9]{64}$');