import {describe,expect,it,vi}from"vitest";
import {createBudgetCeilingPolicyHttpHandler}from"@/server/budget-ceiling-policy-http";
const actor={principal:{workspaceId:"00000000-0000-4000-8000-000000000001",workspaceRef:"workspace_1234567890abcdef",actor:{userId:"00000000-0000-4000-8000-000000000002",actorRef:"actor_owner",role:"owner"},authority:{canRead:true,canPersist:false,canExecute:false,canWriteMeta:false}},role:"owner" as const};
const command={limitRef:"limit_market",revision:1,previousPolicyHash:null,poolRef:"budget_pool_market",parentLimitRef:null,layer:"market",targetScopeRef:"ad_set_public_123",market:"yerli",currency:"TRY",ceilingDecimal:"1000",effectiveFrom:"2026-08-18T08:00:00.000Z",effectiveTo:"2026-09-18T08:00:00.000Z",state:"published"};
const request=(body:unknown,headers:Record<string,string>={})=>new Request("http://localhost/api/budget-ceiling-policies",{method:"POST",headers:{origin:"http://localhost",cookie:"session=x","sec-fetch-site":"same-origin","x-reklamzeka-intent":"budget-ceiling-policy-publish","content-type":"application/json",...headers},body:JSON.stringify(body)});
describe("budget ceiling policy HTTP",()=>{
 it("publishes only through the trusted actor and exposes no action authority",async()=>{const publish=vi.fn(async()=>({policy:{policyHash:"a".repeat(64)},persistence:"inserted" as const,auditAppended:true}));const response=await createBudgetCeilingPolicyHttpHandler({service:{publish} as never,resolveActor:async()=>actor as never})(request({command}));expect(response.status).toBe(201);expect(publish).toHaveBeenCalledWith(actor.principal.actor.userId,expect.objectContaining({workspaceId:actor.principal.workspaceId}));expect(await response.json()).toMatchObject({authority:{canApprove:false,canExecute:false,canWriteMeta:false}});});
 it("rejects authorization headers and workspace overrides before publication",async()=>{const publish=vi.fn();const handler=createBudgetCeilingPolicyHttpHandler({service:{publish} as never,resolveActor:async()=>actor as never});expect((await handler(request({command},{authorization:"Bearer x"}))).status).toBe(400);expect((await handler(request({command:{...command,workspaceId:actor.principal.workspaceId}}))).status).toBe(400);expect(publish).not.toHaveBeenCalled();});
 it("rejects non-publish roles",async()=>{const publish=vi.fn();const handler=createBudgetCeilingPolicyHttpHandler({service:{publish} as never,resolveActor:async()=>({...actor,role:"analyst"}) as never});expect((await handler(request({command}))).status).toBe(403);expect(publish).not.toHaveBeenCalled();});
});
