import {describe,expect,it,vi}from"vitest";
import {DrizzleCampaignAffectedGeoEvidenceAdapter}from"@/connectors/actions/campaign-affected-geo-evidence-adapter";
import {hashMetaAffectedGeoSourceSubtree,normalizeMetaAffectedGeoCountries,type CanonicalAffectedGeoCountrySnapshot}from"@/domain/meta/affected-geo-country-snapshot";
const ws="11111111-1111-4111-8111-111111111111",account="22222222-2222-4222-8222-222222222222",campaign="33333333-3333-4333-8333-333333333333",h=(x:string)=>x.repeat(64);
const scope={workspaceId:ws,workspaceRef:"workspace_alpha",accountRef:"account_main",campaignRef:"campaign_main",entity:{level:"campaign" as const,ref:"campaign_main"},notBefore:"2026-08-18T08:00:00.000Z",evaluatedAt:"2026-08-18T10:00:00.000Z"};
function snapshot(adSetRef:string,country:string,capturedAt:string,raw:string):CanonicalAffectedGeoCountrySnapshot{const targeting={geo_locations:{countries:[country],location_types:["home"]}};const found=normalizeMetaAffectedGeoCountries({sourceKind:"meta_graph_adset_targeting",scope:{workspaceRef:scope.workspaceRef,accountRef:scope.accountRef,campaignRef:scope.campaignRef,adSetRef},sourceGraphVersion:"v23.0",fieldCatalogVersion:"catalog-meta/1.0.0",fetchedAt:capturedAt,provenance:{observationRunRef:"observation_sync",sliceRef:"slice_adsets",pageRef:"page_one",rawPayloadHash:h(raw),sourceGeoSubtreeHash:hashMetaAffectedGeoSourceSubtree(targeting)},targeting});if(found.status!=="known")throw new Error("fixture");return found;}
function row(value:CanonicalAffectedGeoCountrySnapshot,adSetId:string){return{ad_account_id:account,account_ref:scope.accountRef,campaign_id:campaign,campaign_ref:scope.campaignRef,ad_set_id:adSetId,ad_set_ref:value.scope.adSetRef,captured_at:value.capturedAt,workspace_ref:scope.workspaceRef,source_graph_version:value.source.sourceGraphVersion,field_catalog_version:value.source.fieldCatalogVersion,raw_payload_hash:value.source.rawPayloadHash,source_geo_subtree_hash:value.source.sourceGeoSubtreeHash,snapshot_hash:value.snapshotHash};}
describe("campaign affected geo aggregate",()=>{
 it("requires every live ad set and binds the union to every exact snapshot",async()=>{const a=snapshot("adset_one","TR","2026-08-18T09:00:00.000Z","a"),b=snapshot("adset_two","DE","2026-08-18T09:30:00.000Z","b");const execute=vi.fn(async()=>({rows:[row(a,"44444444-4444-4444-8444-444444444444"),row(b,"55555555-5555-4555-8555-555555555555")]}));const resolveExactReadOnly=vi.fn(async(identity:{adSetRef:string})=>identity.adSetRef==="adset_one"?a:b);const result=await new DrizzleCampaignAffectedGeoEvidenceAdapter({execute} as never,ws,scope.workspaceRef,{resolveExactReadOnly} as never).resolveCandidates(scope);expect(result).toHaveLength(1);expect(result[0]).toMatchObject({entity:scope.entity,capturedAt:b.capturedAt});expect((result[0] as any).geoRefs).toHaveLength(2);expect((result[0] as any).sourceRevisions).toHaveLength(2);expect(resolveExactReadOnly).toHaveBeenCalledTimes(2);});
 it("fails closed when any live child lacks or mismatches canonical snapshot evidence",async()=>{const a=snapshot("adset_one","TR","2026-08-18T09:00:00.000Z","a");const missing={...row(a,"44444444-4444-4444-8444-444444444444"),snapshot_hash:null};const adapter=new DrizzleCampaignAffectedGeoEvidenceAdapter({execute:vi.fn(async()=>({rows:[missing]}))} as never,ws,scope.workspaceRef,{resolveExactReadOnly:vi.fn()} as never);expect(await adapter.resolveCandidates(scope)).toEqual([]);});
});
