import { describe, expect, it } from "vitest";
import { buildCanonicalPerformanceReadModel } from "@/domain/meta/performance-read-model";
import { normalizeMetaDailyInsight } from "@/domain/meta/insights/contract";
import { metaPublicReference } from "@/domain/meta/public-reference";
const workspaceId = "11111111-1111-4111-8111-111111111111";
function row(date: string, currency = "TRY") { return normalizeMetaDailyInsight({ schemaVersion: 1, workspaceId, metaConnectionId: "c", adAccountId: "a", entityLevel: "campaign", externalEntityId: "cmp", dateStart: date, dateStop: date, attributionLabel: "7d_click", currency, sourceRevision: date, sourcePayloadHash: "hash", metricProvenance: {}, sourceUpdatedAt: `${date}T12:00:00.000Z`, metrics: [{ metricKey: "spend", aggregation: "additive", valueMinor: 10000, currency, provenance: {} }, { metricKey: "actions", actionType: "lead", aggregation: "additive", valueDecimal: "2", provenance: {} }] }); }
describe("canonical performance read model", () => {
  it("uses exact lead action, mirror-compatible tenant refs and no authority", () => { const source = Array.from({ length: 7 }, (_, index) => ({ accountId: "a", accountName: "A", campaignId: "cmp", campaignName: "Kampanya", row: row(`2026-08-${String(index + 1).padStart(2, "0")}`) })); const result = buildCanonicalPerformanceReadModel(source, workspaceId); const window = result.accounts[0]!.windows[0]!; expect(window).toMatchObject({ state: "ready", observedDays: 7, spend: { valueDecimal: "70000", currency: "TRY" }, outcome: { valueDecimal: "14" }, cpa: { valueDecimal: "5000", currency: "TRY" } }); expect(result.authority).toEqual({ actionAuthority: "none", canPublish: false, canApprove: false, canExecute: false, canWriteMeta: false }); expect(result.accounts[0]!.campaigns[0]!.campaignRef).toBe(metaPublicReference("campaign", workspaceId, "cmp")); });
  it("fails closed on incomplete or mixed-currency monetary windows", () => { const partial = buildCanonicalPerformanceReadModel([{ accountId: "a", accountName: "A", campaignId: "cmp", campaignName: "K", row: row("2026-08-07") }]).accounts[0]!.windows[0]!; expect(partial).toMatchObject({ state: "partial", spend: null, outcome: null }); expect(partial.reasonCodes).toContain("coverage_incomplete"); const mixed = buildCanonicalPerformanceReadModel(Array.from({ length: 7 }, (_, index) => ({ accountId: "a", accountName: "A", campaignId: "cmp", campaignName: "K", row: row(`2026-08-${String(index + 1).padStart(2, "0")}`, index ? "TRY" : "USD") }))).accounts[0]!.windows[0]!; expect(mixed.reasonCodes).toContain("mixed_currency"); expect(mixed.spend).toBeNull(); });
});
