import { describe,expect,it,vi } from "vitest";
import { createNamingTemplateHttpHandlers } from "@/server/naming-template-http";
import { createNamingTemplateRevision } from "@/domain/campaigns/naming-template";
const revision=createNamingTemplateRevision({workspaceRef:`workspace_${"a".repeat(24)}`,accountRef:`account_${"b".repeat(24)}`,templateRef:"naming_template_http",revision:1,previousRevisionHash:null,state:"draft",namingFamily:"http",entityLevel:"campaign",nameRules:[{source:"campaign_name",match:"all",tokens:["launch"]}],corroboration:[{kind:"objective",operator:"equals",expected:["sales"]}],proposedAssignments:[{dimensionRef:`dimension_${"c".repeat(24)}`,definitionRef:`category_${"d".repeat(24)}`}]});
const request=(method:string,intent:string,body?:unknown,url=`http://localhost:3000/api/naming-templates`)=>new Request(url,{method,headers:{cookie:"session=x","sec-fetch-site":"same-origin","x-reklamzeka-intent":intent,...(body?{"content-type":"application/json","content-length":String(JSON.stringify(body).length)}:{})},body:body?JSON.stringify(body):undefined});
describe("naming template HTTP",()=>{
  it("binds actor/workspace server-side and returns no-authority evidence",async()=>{const save=vi.fn(async(value)=>({revision:{...revision,workspaceRef:value.workspaceId},replay:false}));const handlers=createNamingTemplateHttpHandlers({repository:{save,list:vi.fn(async()=>[])},replay:{replay:vi.fn()},identity:async()=>({workspaceId:"00000000-0000-4000-8000-000000000001",actorId:"00000000-0000-4000-8000-000000000002"})} as never);const body={accountRef:revision.accountRef,templateRef:revision.templateRef,commandRef:`naming_template_command_${"e".repeat(64)}`,expectedRevision:null,state:"draft",namingFamily:"http",entityLevel:"campaign",nameRules:revision.nameRules,corroboration:revision.corroboration,proposedAssignments:revision.proposedAssignments};const response=await handlers.POST(request("POST","naming-template-save",body));expect(response.status).toBe(201);expect(save).toHaveBeenCalledWith(expect.objectContaining({workspaceId:"00000000-0000-4000-8000-000000000001",actorId:"00000000-0000-4000-8000-000000000002"}));expect(response.headers.get("x-reklamzeka-meta-write")).toBe("disabled");});
  it("previews only a unique published current template",async()=>{const published=createNamingTemplateRevision({...revision,revision:2,previousRevisionHash:revision.revisionHash,state:"published"});const replay=vi.fn(async()=>({status:"candidate"}));const handlers=createNamingTemplateHttpHandlers({repository:{save:vi.fn(),list:vi.fn(async()=>[published])},replay:{replay},identity:async()=>({workspaceId:"00000000-0000-4000-8000-000000000001",actorId:"00000000-0000-4000-8000-000000000002"})} as never);const response=await handlers.POST(request("POST","naming-template-preview",{accountRef:published.accountRef,templateRef:published.templateRef,entityRef:`campaign_${"f".repeat(24)}`}));expect(response.status).toBe(200);expect(replay).toHaveBeenCalledOnce();});
  it("rejects auth headers, cross-site calls and malformed selectors",async()=>{const handlers=createNamingTemplateHttpHandlers({repository:{save:vi.fn(),list:vi.fn(async()=>[])},replay:{replay:vi.fn()},identity:async()=>({workspaceId:"00000000-0000-4000-8000-000000000001",actorId:"00000000-0000-4000-8000-000000000002"})} as never);expect((await handlers.GET(new Request(`http://localhost:3000/api/naming-templates?account=${revision.accountRef}`,{headers:{cookie:"x","sec-fetch-site":"cross-site","x-reklamzeka-intent":"naming-template-list"}}))).status).toBe(400);expect((await handlers.POST(request("POST","naming-template-preview",{accountRef:"bad",templateRef:"bad",entityRef:"bad"}))).status).toBe(400);});
});
