import { describe, expect, it } from "vitest";
import { runP06ExecutionV2, type P06ExecutionV2Value } from "@/domain/actions/p06-execution-v2";

const request = { executionRef: "execution_main", workspaceRef: "workspace_main", accountRef: "account_main", entityRef: "adset_main", action: "status_pause" as const, expectedBefore: { status: "ACTIVE" as const, budgetMinor: 100 }, desired: { status: "PAUSED" as const, budgetMinor: 100 }, leaseTokenHash: "a".repeat(64), fenceHash: "b".repeat(64), evaluatedAt: "2026-08-18T12:00:00.000Z" };
function writer(values: P06ExecutionV2Value[], write: "written" | "ambiguous_transport" = "written") { let reads = 0, writes = 0; return { port: { read: async () => values[Math.min(reads++, values.length - 1)]!, write: async () => { writes++; return write; } }, counts: () => ({ reads, writes }) }; }
describe("P06 execution v2", () => {
  it("is default-off before all writer operations", async () => { const w = writer([request.expectedBefore]); const out = await runP06ExecutionV2({ request, writer: w.port }); expect(out.outcome).toBe("disabled"); expect(w.counts()).toEqual({ reads: 0, writes: 0 }); });
  it("enforces workspace/account/action allowlists", async () => { const w = writer([request.expectedBefore]); const out = await runP06ExecutionV2({ request, gate: { enabled: true, workspaceAllowlist: [request.workspaceRef], accountAllowlist: [request.accountRef], actionAllowlist: ["budget_decrease"] }, writer: w.port }); expect(out.writes).toBe(0); expect(w.counts()).toEqual({ reads: 0, writes: 0 }); });
  it("reads first and never writes an already applied target", async () => { const w = writer([request.desired]); const out = await runP06ExecutionV2({ request, gate: { enabled: true }, writer: w.port }); expect(out.outcome).toBe("already_applied_no_write"); expect(w.counts()).toEqual({ reads: 1, writes: 0 }); });
  it("rejects stale expected-before without mutation", async () => { const w = writer([{ status: "ACTIVE", budgetMinor: 99 }]); const out = await runP06ExecutionV2({ request, gate: { enabled: true }, writer: w.port }); expect(out.outcome).toBe("expected_before_mismatch"); expect(w.counts()).toEqual({ reads: 1, writes: 0 }); });
  it("performs exactly one typed write and verifies", async () => { const w = writer([request.expectedBefore, request.desired]); const out = await runP06ExecutionV2({ request, gate: { enabled: true }, writer: w.port }); expect(out.outcome).toBe("written_verified"); expect(out.steps).toEqual(["lease", "idempotency", "current_read", "expected_before", "typed_mutation", "read_after_write", "immutable_terminal", "release"]); expect(w.counts()).toEqual({ reads: 2, writes: 1 }); });
  it("reads after ambiguous transport and never retries blindly", async () => { const w = writer([request.expectedBefore, request.desired], "ambiguous_transport"); const out = await runP06ExecutionV2({ request, gate: { enabled: true }, writer: w.port }); expect(out.outcome).toBe("ambiguous_resolved"); expect(w.counts()).toEqual({ reads: 2, writes: 1 }); });
  it("emits immutable rollback proposal from execution-time observation", async () => { const observed = { status: "ACTIVE" as const, budgetMinor: 77 }; const w = writer([request.expectedBefore, observed]); const out = await runP06ExecutionV2({ request, gate: { enabled: true }, writer: w.port }); expect(out.outcome).toBe("verification_failed"); expect(out.rollbackProposal).toEqual({ observed, desired: request.desired }); expect(Object.isFrozen(out)).toBe(true); });
  it("kills execution before reads", async () => { const w = writer([request.expectedBefore]); const out = await runP06ExecutionV2({ request, gate: { enabled: true, killSwitch: true }, writer: w.port }); expect(out.outcome).toBe("disabled"); expect(w.counts()).toEqual({ reads: 0, writes: 0 }); });
});
