import { describe, expect, it } from "vitest";
import { buildActionPlan } from "@/domain/actions/autonomy-valve";
import { createMetaWriteSpec } from "@/domain/actions/meta-write-spec";
import { createP06BudgetExecutionMaterialization, p06BudgetDecimalToMinor } from "@/domain/actions/p06-budget-execution-materialization";
import { p06ExecutionV2Digest } from "@/domain/actions/p06-execution-v2";
import type { ActionExecutionAdmission } from "@/domain/actions/action-execution-admission";

const unitHash="a".repeat(64), at="2026-08-18T10:00:00.000Z";
const plan=buildActionPlan({kind:"budget_change",entity:{level:"adset",ref:"adset_12345"},budgetKind:"lifetime",currency:"TRY",beforeDecimal:"100.50",afterDecimal:"90.25",budgetOwnerRef:"adset_12345"},{workspaceRef:"workspace_main",accountGroupRef:null,accountRef:"account_main",internalCategoryRefs:[],campaignRef:"campaign_12345",entity:{level:"adset",ref:"adset_12345"},evaluatedAt:at,rules:[],budgetLimits:{currency:"TRY",maximumAbsoluteDeltaDecimal:"20.25",maximumRelativeDeltaBasisPoints:2000,limitRefs:["limit_main"]},protection:{protectedInternalCategoryRefs:[],affectedGeoRefs:[],protectedGeoRefs:[],changeDisposition:"allowed",policyRefs:[]}});
function admission():ActionExecutionAdmission{const writeSpec=createMetaWriteSpec({unitRef:"action_unit_11111111111111111111",unitHash,actionPlan:plan});const core={version:"action-execution-admission/1.0.0" as const,unitRef:writeSpec.unitRef,approvalDecisionRef:"decision_one",approvalGrantRef:"grant_one",executionPresenceRef:"presence_one",writeSpec,eligibilitySnapshotHash:"b".repeat(64),eligibilityHash:"c".repeat(64),dependencyUnitRefs:Object.freeze([]),evaluatedAt:at,disposition:"admitted_for_disabled_executor" as const,capabilities:Object.freeze({canExecute:false as const,canWriteMeta:false as const,canDispatchNetwork:false as const})};return Object.freeze({...core,admissionHash:p06ExecutionV2Digest(core)});}
describe("P06 budget execution materialization",()=>{
 it("converts a fully bound admitted Guide budget action to an authority-free request seed",()=>{expect(createP06BudgetExecutionMaterialization({admission:admission(),actionPlan:plan,unitHash,workspaceRef:"workspace_main",accountRef:"account_main",currentStatus:"ACTIVE"})).toMatchObject({route:"guide_budget_human_approved",action:"budget_decrease",budgetKind:"lifetime",currency:"TRY",expectedBefore:{status:"ACTIVE",budgetMinor:10050},desired:{status:"ACTIVE",budgetMinor:9025},authority:{canExecute:false,canWriteMeta:false,canDispatchNetwork:false}});});
 it("uses exact minor conversion and rejects unsupported precision/currencies",()=>{expect(p06BudgetDecimalToMinor("1.05","TRY")).toBe(105);expect(()=>p06BudgetDecimalToMinor("1.005","TRY")).toThrow("invalid_input");expect(()=>p06BudgetDecimalToMinor("1","JPY")).toThrow("unsupported_currency");});
 it("rejects an admission/action-plan mismatch",()=>{expect(()=>createP06BudgetExecutionMaterialization({admission:{...admission(),writeSpec:{...admission().writeSpec,specHash:"f".repeat(64)}} as ActionExecutionAdmission,actionPlan:plan,unitHash,workspaceRef:"workspace_main",accountRef:"account_main",currentStatus:"ACTIVE"})).toThrow();});
});
