import { describe, expect, it } from "vitest";
import { createSliceRuleWorkspaceDraft } from "@/application/slice-rule-workspace-service";
import { evaluateTemporalRecommendation } from "@/application/temporal-recommendation-service";
import { TemporalRecommendationDrizzleAdapter } from "@/connectors/decisions/temporal-recommendation-drizzle-adapter";
import { openDeliveryHealthAlertLedger } from "@/domain/meta/delivery-health-alert-ledger";
import type { DecisionLedger } from "@/domain/decisions/ledger";

const workspaceRef = "workspace_primary";
const workspaceId = "00000000-0000-4000-8000-000000000001";
function draft() { return createSliceRuleWorkspaceDraft({ workspaceId, seriesRef: "series_primary", revision: 1, previousDraftHash: "GENESIS", idempotencyKey: "draft_primary", createdAt: "2026-08-10T00:00:00.000Z", scope: { market: "international", serviceRef: "service_primary", campaignFamilyRef: "family_primary" }, rule: { kind: "degerlendirme_kumesi", grup_boyutlari: ["pazar"], eksik_kunye: "degerlendirme_disi_tut" }, priority: 1, verification: { metric: "qualified_leads", reviewCadence: "daily", rollbackWhen: "guardrail" } }); }
function alert() { return openDeliveryHealthAlertLedger({ actorRef: "actor_detector", alert: { workspaceRef, alertRef: "delivery_alert_primary", accountRef: "account_primary", assignedActorRef: "actor_owner", detectedAt: "2026-08-10T00:00:00.000Z", evidence: { level: "confirmed", officialState: "delivery_limited", sourceRef: "source_primary" }, policy: null, frozenContextHash: null } }); }
function memory() { let ledger: DecisionLedger = []; return { readLedger: async () => ledger, appendSuffix: async (input: { ledger: DecisionLedger }) => { ledger = input.ledger; }, ledger: () => ledger }; }
function input(openDeliveryAlerts: readonly ReturnType<typeof alert>[] = []) { return { workspaceRef, occurredAt: "2026-08-12T00:00:00.000Z", frozenContextRef: "a".repeat(64), ruleDraft: draft(), window: { windowRef: "window_primary", accountRef: "account_primary", startedAt: "2026-08-11T00:00:00.000Z", endedAt: "2026-08-12T00:00:00.000Z", settled: true, evidenceRefs: ["evidence_primary"] }, openDeliveryAlerts }; }

describe("temporal recommendation service", () => {
  it("persists a frozen-context recommendation exactly once with no authority", async () => { const store = memory(); const first = await evaluateTemporalRecommendation(input(), store); const second = await evaluateTemporalRecommendation(input(), store); expect(first).toMatchObject({ outcome: "recommendation", persistence: "inserted", authority: { canPublish: false, canApprove: false, canExecute: false, canWriteMeta: false } }); expect(second.persistence).toBe("unchanged"); expect(store.ledger()).toHaveLength(2); expect(store.ledger()[1]).toMatchObject({ recordType: "decision", disposition: "act", executionAuthority: "none" }); });
  it("turns an open delivery alert into an append-only no-change hold", async () => { const store = memory(); const result = await evaluateTemporalRecommendation(input([alert()]), store); expect(result).toMatchObject({ outcome: "no_change", reason: "open_delivery_alert", heldByAlertRefs: ["delivery_alert_primary"] }); expect(store.ledger()[1]).toMatchObject({ disposition: "no_change", executionAuthority: "none" }); });
  it("records a fresh held evaluation when an alert opens after a prior recommendation", async () => { const store = memory(); await evaluateTemporalRecommendation(input(), store); const held = await evaluateTemporalRecommendation(input([alert()]), store); expect(held).toMatchObject({ outcome: "no_change", persistence: "inserted" }); expect(store.ledger()).toHaveLength(4); });
  it("does not recommend from an unsettled or too-short window", async () => { const store = memory(); const result = await evaluateTemporalRecommendation({ ...input(), window: { ...input().window, settled: false } }, store); expect(result).toMatchObject({ outcome: "no_change", reason: "window_unsettled" }); });
  it("binds only its own workspace to the persistent decision-ledger repository", async () => { const store = memory(); const adapter = new TemporalRecommendationDrizzleAdapter({ load: async () => store.ledger(), appendSuffix: async (value) => { await store.appendSuffix(value); return value.ledger; } }, { workspaceId, workspaceRef }); await expect(evaluateTemporalRecommendation({ ...input(), workspaceRef: "workspace_other" }, adapter)).rejects.toThrow("port_failure"); });
});
