import { sql } from "drizzle-orm";
import type { NodePgDatabase } from "drizzle-orm/node-postgres";
import type { OperationReadRepository } from "@/application/operation-read-service";
import type { OperationRowFact } from "@/domain/operations/operation-read-model";
import * as schema from "@/db/schema";
type Database = NodePgDatabase<typeof schema>; const UUID=/^[0-9a-f-]{36}$/i;
/** Canonical mirror only; no browser selector is interpolated into SQL. */
export class DrizzleOperationReadRepository implements OperationReadRepository {
 constructor(private readonly database: Pick<Database,"transaction">) {}
 async load(input: Parameters<OperationReadRepository["load"]>[0]) { if(!UUID.test(input.workspaceId)) throw new Error("operation read rejected: scope"); return this.database.transaction(async tx=>{ await tx.execute(sql`set local transaction isolation level repeatable read`); await tx.execute(sql`set local transaction read only`);
 const result=await tx.execute(sql`with insight_coverage as (select insight.workspace_id, insight.ad_account_id, insight.external_entity_id, array_agg(distinct insight.date_start order by insight.date_start)::text[] observed_days from meta_daily_insights insight where insight.workspace_id=${input.workspaceId}::uuid and insight.entity_level='campaign' and insight.date_start>=${input.period.startDate}::date and insight.date_stop<=${input.period.endDate}::date group by insight.workspace_id,insight.ad_account_id,insight.external_entity_id) select campaign.id::text campaign_id,campaign.external_campaign_id,campaign.name campaign_name,account.id::text account_id,account.name account_name,adset.id::text adset_id,adset.name adset_name,campaign.campaign_budget_optimization cbo,campaign.daily_budget_minor campaign_budget,adset.daily_budget_minor adset_budget,org.id::text org_id,org.label org_name,market.key market,coalesce(coverage.observed_days,array[]::text[]) observed_days from ad_campaigns campaign join ad_accounts account on account.id=campaign.ad_account_id and account.workspace_id=campaign.workspace_id left join meta_ad_sets adset on adset.workspace_id=campaign.workspace_id and adset.campaign_id=campaign.id and adset.disappeared_at is null left join organization_campaign_meta_memberships membership on membership.workspace_id=campaign.workspace_id and membership.campaign_id=campaign.id and membership.effective_to is null left join organization_campaigns org on org.id=membership.organization_campaign_id and org.workspace_id=campaign.workspace_id left join category_definitions market on market.id=org.market_definition_id and market.workspace_id=org.workspace_id left join insight_coverage coverage on coverage.workspace_id=campaign.workspace_id and coverage.ad_account_id=campaign.ad_account_id and coverage.external_entity_id=campaign.external_campaign_id where campaign.workspace_id=${input.workspaceId}::uuid and campaign.disappeared_at is null and (${input.sliceRef}::text is null or exists(select 1 from slices slice join slice_resolution_snapshots snapshot on snapshot.workspace_id=slice.workspace_id and snapshot.slice_revision_id=slice.current_published_revision_id join slice_resolution_snapshot_members member on member.workspace_id=snapshot.workspace_id and member.snapshot_id=snapshot.id where slice.workspace_id=campaign.workspace_id and slice.slice_ref=${input.sliceRef} and (member.campaign_id=campaign.id or member.ad_set_id=adset.id))) order by campaign.name,campaign.id,adset.id nulls first limit ${input.limit + 1}`) as {rows:any[]};
 const expectedDays=Array.from({length:Math.floor((Date.parse(`${input.period.endDate}T00:00:00Z`)-Date.parse(`${input.period.startDate}T00:00:00Z`))/86400000)+1},(_,i)=>new Date(Date.parse(`${input.period.startDate}T00:00:00Z`)+i*86400000).toISOString().slice(0,10)); const facts:OperationRowFact[]=result.rows.slice(0,input.limit).map(row=>{const observedDays=(row.observed_days as string[]).sort();const missingDays=expectedDays.filter(day=>!observedDays.includes(day));return {workspaceId:input.workspaceId,market:row.market==='yerli'||row.market==='yabanci'?row.market:null,accountId:row.account_id,accountName:row.account_name,campaignId:row.campaign_id,campaignName:row.campaign_name,organizationCampaignId:row.org_id,organizationCampaignName:row.org_name,adSetId:row.adset_id,adSetName:row.adset_name,cbo:row.cbo===true?true:row.cbo===false?false:null,campaignBudgetMinor:row.campaign_budget===null?null:Number(row.campaign_budget),adSetBudgetMinor:row.adset_budget===null?null:Number(row.adset_budget),spendMinor:null,observedDays,missingDays,reasonCodes:missingDays.length?["coverage_incomplete"]:[],primaryResultBinding:{state:"unbound"},primaryResult:null,primaryResultCostMinor:null}});
 return Object.freeze({facts:Object.freeze(facts),unavailable:false,nextCursor:result.rows.length>input.limit?"operation_cursor_more":null}); }); }
}
