import { sql } from "drizzle-orm";
import type { NodePgDatabase } from "drizzle-orm/node-postgres";
import type { OperationReadRepository } from "@/application/operation-read-service";
import type { OperationRowFact } from "@/domain/operations/operation-read-model";
import * as schema from "@/db/schema";
type Database = NodePgDatabase<typeof schema>; const UUID=/^[0-9a-f-]{36}$/i;
/** Canonical mirror only; no browser selector is interpolated into SQL. */
export class DrizzleOperationReadRepository implements OperationReadRepository {
 constructor(private readonly database: Pick<Database,"transaction">) {}
 async load(input: Parameters<OperationReadRepository["load"]>[0]) { if(!UUID.test(input.workspaceId)) throw new Error("operation read rejected: scope"); return this.database.transaction(async tx=>{ await tx.execute(sql`set local transaction isolation level repeatable read`); await tx.execute(sql`set local transaction read only`);
 const result=await tx.execute(sql`select campaign.id::text campaign_id,campaign.name campaign_name,account.id::text account_id,account.name account_name,adset.id::text adset_id,adset.name adset_name,campaign.campaign_budget_optimization cbo,campaign.daily_budget_minor campaign_budget,adset.daily_budget_minor adset_budget,org.id::text org_id,org.label org_name,market.key market from ad_campaigns campaign join ad_accounts account on account.id=campaign.ad_account_id and account.workspace_id=campaign.workspace_id left join meta_ad_sets adset on adset.workspace_id=campaign.workspace_id and adset.campaign_id=campaign.id and adset.disappeared_at is null left join organization_campaign_meta_memberships membership on membership.workspace_id=campaign.workspace_id and membership.campaign_id=campaign.id and membership.effective_to is null left join organization_campaigns org on org.id=membership.organization_campaign_id and org.workspace_id=campaign.workspace_id left join category_definitions market on market.id=org.market_definition_id and market.workspace_id=org.workspace_id where campaign.workspace_id=${input.workspaceId}::uuid and campaign.disappeared_at is null order by campaign.id,adset.id nulls first limit ${input.limit + 1}`) as {rows:any[]};
 const missingDays=Array.from({length:Math.floor((Date.parse(`${input.period.endDate}T00:00:00Z`)-Date.parse(`${input.period.startDate}T00:00:00Z`))/86400000)+1},(_,i)=>new Date(Date.parse(`${input.period.startDate}T00:00:00Z`)+i*86400000).toISOString().slice(0,10)); const facts:OperationRowFact[]=result.rows.slice(0,input.limit).map(row=>({workspaceId:input.workspaceId,market:row.market==='yerli'||row.market==='yabanci'?row.market:null,accountId:row.account_id,accountName:row.account_name,campaignId:row.campaign_id,campaignName:row.campaign_name,organizationCampaignId:row.org_id,organizationCampaignName:row.org_name,adSetId:row.adset_id,adSetName:row.adset_name,cbo:row.cbo===true?true:row.cbo===false?false:null,campaignBudgetMinor:row.campaign_budget===null?null:Number(row.campaign_budget),adSetBudgetMinor:row.adset_budget===null?null:Number(row.adset_budget),spendMinor:null,observedDays:[],missingDays,reasonCodes:["canonical_insights_not_loaded"],primaryResultBinding:{state:"unbound"},primaryResult:null,primaryResultCostMinor:null}));
 return Object.freeze({facts:Object.freeze(facts),unavailable:false,nextCursor:result.rows.length>input.limit?"operation_cursor_more":null}); }); }
}
