import { createHash } from "node:crypto";
import type { GuideAction } from "@/domain/guides/guide-revision";
export const P06_EXECUTION_V2_VERSION="p06-execution-v2/1.0.0" as const;
export type P06ExecutionV2Action=Extract<GuideAction,"status_pause"|"status_activate"|"budget_decrease"|"budget_increase">;
export type P06ExecutionV2Value=Readonly<{status:"ACTIVE"|"PAUSED";budgetMinor:number|null}>;
export type P06ExecutionV2Request=Readonly<{executionRef:string;workspaceRef:string;accountRef:string;entityRef:string;action:P06ExecutionV2Action;expectedBefore:P06ExecutionV2Value;desired:P06ExecutionV2Value;leaseTokenHash:string;fenceHash:string;evaluatedAt:string}>;
export type P06ExecutionV2Gate=Readonly<{enabled:true;killSwitch:false;workspaceAllowlist:readonly string[];accountAllowlist:readonly string[];actionAllowlist:readonly P06ExecutionV2Action[];snapshotHash:string}>;
export type P06ExecutionV2Writer=Readonly<{read(x:Readonly<{workspaceRef:string;accountRef:string;entityRef:string}>):Promise<P06ExecutionV2Value>;write(x:Readonly<{request:P06ExecutionV2Request;idempotencyKey:string}>):Promise<Readonly<{kind:"written"|"ambiguous_transport";receiptHash:string}>>}>;
export type P06ExecutionV2Control=Readonly<{gate(x:Readonly<{phase:"staging"|"admission"|"post_claim"|"pre_dispatch"|"read_after_write";request:P06ExecutionV2Request}>):Promise<P06ExecutionV2Gate>;claim(x:Readonly<{executionRef:string;leaseTokenHash:string;fenceHash:string}>):Promise<Readonly<{owned:true;receiptHash:string}>>;terminal(x:Readonly<{executionRef:string;outcome:string;writeReceiptHash:string|null}>):Promise<Readonly<{receiptHash:string}>>;release(x:Readonly<{executionRef:string;leaseTokenHash:string;fenceHash:string}>):Promise<void>}>;
export type P06ExecutionV2Result=Readonly<{version:typeof P06_EXECUTION_V2_VERSION;executionRef:string;outcome:"disabled"|"already_applied_no_write"|"expected_before_mismatch"|"written_verified"|"ambiguous_resolved"|"verification_failed";writes:0|1;terminalHash:string;release:"released";rollbackProposal:unknown;steps:readonly string[]}>;
const H=/^[a-f0-9]{64}$/;const h=(x:unknown)=>createHash("sha256").update(JSON.stringify(x)).digest("hex");const same=(a:P06ExecutionV2Value,b:P06ExecutionV2Value)=>a.status===b.status&&a.budgetMinor===b.budgetMinor;const valid=(x:P06ExecutionV2Value)=>(x.status==="ACTIVE"||x.status==="PAUSED")&&(x.budgetMinor===null||(Number.isSafeInteger(x.budgetMinor)&&x.budgetMinor>=0));
const coherent=(r:P06ExecutionV2Request)=>valid(r.expectedBefore)&&valid(r.desired)&&(r.action==="status_pause"?r.expectedBefore.status==="ACTIVE"&&r.desired.status==="PAUSED"&&r.expectedBefore.budgetMinor===r.desired.budgetMinor:r.action==="status_activate"?r.expectedBefore.status==="PAUSED"&&r.desired.status==="ACTIVE"&&r.expectedBefore.budgetMinor===r.desired.budgetMinor:r.expectedBefore.status===r.desired.status&&r.expectedBefore.budgetMinor!==null&&r.desired.budgetMinor!==null&&(r.action==="budget_decrease"?r.desired.budgetMinor<r.expectedBefore.budgetMinor:r.desired.budgetMinor>r.expectedBefore.budgetMinor));
export async function runP06ExecutionV2({request:r,writer,control}:Readonly<{request:P06ExecutionV2Request;writer:P06ExecutionV2Writer;control:P06ExecutionV2Control}>):Promise<P06ExecutionV2Result>{if(!H.test(r.leaseTokenHash)||!H.test(r.fenceHash)||!coherent(r))throw Error("p06 execution v2 invalid input");let writes:0|1=0,outcome:P06ExecutionV2Result["outcome"]="disabled",receipt:string|null=null,previous:P06ExecutionV2Value|null=null,post:P06ExecutionV2Value|null=null;const steps:string[]=[];const gate=async(phase:Parameters<P06ExecutionV2Control["gate"]>[0]["phase"])=>{const g=await control.gate({phase,request:r});return g.enabled&&!g.killSwitch&&H.test(g.snapshotHash)&&g.workspaceAllowlist.includes(r.workspaceRef)&&g.accountAllowlist.includes(r.accountRef)&&g.actionAllowlist.includes(r.action)};const done=async()=>{steps.push("immutable_terminal");const t=await control.terminal({executionRef:r.executionRef,outcome,writeReceiptHash:receipt});steps.push("release");await control.release({executionRef:r.executionRef,leaseTokenHash:r.leaseTokenHash,fenceHash:r.fenceHash});return Object.freeze({version:P06_EXECUTION_V2_VERSION,executionRef:r.executionRef,outcome,writes,terminalHash:t.receiptHash,release:"released" as const,rollbackProposal:outcome==="verification_failed"&&previous&&post&&receipt?{executionRef:r.executionRef,terminalHash:t.receiptHash,writeReceiptHash:receipt,previousObserved:previous,postWriteObserved:post,desired:r.desired}:null,steps:Object.freeze(steps)})};steps.push("staging_gate");if(!await gate("staging"))return done();steps.push("admission_gate");if(!await gate("admission"))return done();steps.push("lease_fence_claim");await control.claim({executionRef:r.executionRef,leaseTokenHash:r.leaseTokenHash,fenceHash:r.fenceHash});steps.push("idempotency","post_claim_gate");if(!await gate("post_claim"))return done();steps.push("current_read");previous=await writer.read({workspaceRef:r.workspaceRef,accountRef:r.accountRef,entityRef:r.entityRef});if(same(previous,r.desired)){outcome="already_applied_no_write";return done()}steps.push("expected_before");if(!same(previous,r.expectedBefore)){outcome="expected_before_mismatch";return done()}steps.push("pre_dispatch_gate");if(!await gate("pre_dispatch"))return done();steps.push("typed_mutation");const w=await writer.write({request:r,idempotencyKey:h({r})});receipt=w.receiptHash;writes=1;steps.push(w.kind==="ambiguous_transport"?"ambiguous_read_before_retry":"read_after_write");post=await writer.read({workspaceRef:r.workspaceRef,accountRef:r.accountRef,entityRef:r.entityRef});steps.push("read_after_write_gate");if(!await gate("read_after_write"))return done();outcome=same(post,r.desired)?w.kind==="ambiguous_transport"?"ambiguous_resolved":"written_verified":"verification_failed";return done()}
