import { sql } from "drizzle-orm";
import type { NodePgDatabase } from "drizzle-orm/node-postgres";
import { interviewKitHash, newInterviewKitRef, type InterviewKit, type InterviewKitRepository, type OfficialSourceOption } from "@/application/interview-kit-service";
import { isOfficialGuidanceSourceUrl } from "@/domain/guidance/registry";
import * as schema from "@/db/schema";
type DB = NodePgDatabase<typeof schema>; type Executor = Pick<DB,"execute">; type Tx = Pick<DB,"execute"|"transaction">;
const rows=<T>(x:unknown):readonly T[]=>{if(!x||typeof x!=="object"||!("rows"in x)||!Array.isArray(x.rows))throw new Error("corrupt_store");return x.rows as readonly T[]};
const one=<T>(x:readonly T[],code:string)=>{if(x.length!==1)throw new Error(code);return x[0]!};
type Source=Readonly<{id:string;option_id:string;title:string;url:string;version:number;record_hash:string;review_by:string}>;
type Head=Readonly<{revision:number;kit_hash:string;source_id:string;source_snapshot:unknown;payload:unknown;state:string}>;
async function sourceOption(executor:Executor,workspaceId:string,optionId:string){const source=one(rows<Source>(await executor.execute(sql`select id, id::text option_id, title, source_url url, version, record_hash, review_by from guidance_sources where workspace_id=${workspaceId}::uuid and id::text=${optionId} and source_type='official_meta_guidance' and status='published' and review_by > now() and source_url is not null limit 2`)),"source_not_found");if(!isOfficialGuidanceSourceUrl(source.url))throw new Error("source_not_found");return source;}
function project(row:Readonly<{kit_ref:string;revision:number;state:string;payload:unknown;source_snapshot:unknown}>):InterviewKit { const p=row.payload as any,s=row.source_snapshot as any; if(!p||!s||!Array.isArray(p.questions)||!p.applicability)throw new Error("corrupt_store"); return Object.freeze({kitRef:row.kit_ref,revision:row.revision,state:row.state as "active"|"archived",name:p.name,explanation:p.explanation,questions:Object.freeze(p.questions),applicability:Object.freeze({pages:Object.freeze(p.applicability.pages),intents:Object.freeze(p.applicability.intents)}),source:Object.freeze({optionId:s.optionId,title:s.title,url:s.url,freshness:"fresh"})}); }
function snapshot(source:Source){return Object.freeze({optionId:source.option_id,title:source.title,url:source.url,version:source.version,recordHash:source.record_hash,reviewBy:new Date(source.review_by).toISOString()});}
async function head(executor:Executor,w:string,ref:string){const row=one(rows<Head>(await executor.execute(sql`select revision,kit_hash,source_id,source_snapshot,payload,state from orchestrator_interview_kit_revisions where workspace_id=${w}::uuid and kit_ref=${ref} order by revision desc limit 1 for update`)),"kit_not_found");if(row.state!=="active")throw new Error("stale_head");return row;}
export class DrizzleInterviewKitRepository implements InterviewKitRepository {
  constructor(private readonly db:Tx){}
  async sources(w:string){const result=rows<Source>(await this.db.execute(sql`select id::text option_id,title,source_url url,version,record_hash,review_by,id from (select distinct on(source_key) * from guidance_sources where workspace_id=${w}::uuid order by source_key,version desc) source where source_type='official_meta_guidance' and status='published' and review_by>now() and source_url is not null order by title limit 50`));return Object.freeze(result.filter(x=>isOfficialGuidanceSourceUrl(x.url)).map(x=>Object.freeze({optionId:x.option_id,title:x.title,url:x.url,freshness:"fresh" as const})));}
  async list(w:string){const result=rows<any>(await this.db.execute(sql`select kit_ref,revision,state,payload,source_snapshot from (select distinct on(kit_ref) kit_ref,revision,state,payload,source_snapshot from orchestrator_interview_kit_revisions where workspace_id=${w}::uuid order by kit_ref,revision desc) current where state='active' order by kit_ref limit 50`));return Object.freeze(result.map(project));}
  async create(i:Parameters<InterviewKitRepository["create"]>[0]){return this.db.transaction(async tx=>{const source=await sourceOption(tx,i.workspaceId,i.sourceOptionId);const payload={name:i.name,explanation:i.explanation,questions:i.questions,applicability:{pages:i.pages,intents:i.intents}};const s=snapshot(source),ref=newInterviewKitRef(),hash=interviewKitHash({payload,source:s,state:"active"});const inserted=one(rows<any>(await tx.execute(sql`insert into orchestrator_interview_kit_revisions(workspace_id,kit_ref,revision,previous_hash,kit_hash,state,source_id,source_snapshot,payload,created_by_actor_id) values(${i.workspaceId}::uuid,${ref},1,'GENESIS',${hash},'active',${source.id}::uuid,${JSON.stringify(s)}::jsonb,${JSON.stringify(payload)}::jsonb,${i.actorId}::uuid) returning kit_ref,revision,state,payload,source_snapshot`)),"write_conflict");return project(inserted);});}
  async revise(i:Parameters<InterviewKitRepository["revise"]>[0]){return this.db.transaction(async tx=>{await tx.execute(sql`select pg_advisory_xact_lock(hashtextextended(${`interview-kit:${i.workspaceId}:${i.kitRef}`},0))`);const current=await head(tx,i.workspaceId,i.kitRef);if(current.revision!==i.expectedRevision)throw new Error("stale_head");const source=await sourceOption(tx,i.workspaceId,i.sourceOptionId);const payload={name:i.name,explanation:i.explanation,questions:i.questions,applicability:{pages:i.pages,intents:i.intents}},s=snapshot(source),hash=interviewKitHash({payload,source:s,state:"active"});if(hash===current.kit_hash)throw new Error("duplicate_revision");const inserted=one(rows<any>(await tx.execute(sql`insert into orchestrator_interview_kit_revisions(workspace_id,kit_ref,revision,previous_hash,kit_hash,state,source_id,source_snapshot,payload,created_by_actor_id) values(${i.workspaceId}::uuid,${i.kitRef},${current.revision+1},${current.kit_hash},${hash},'active',${source.id}::uuid,${JSON.stringify(s)}::jsonb,${JSON.stringify(payload)}::jsonb,${i.actorId}::uuid) returning kit_ref,revision,state,payload,source_snapshot`)),"write_conflict");return project(inserted);});}
  async archive(i:Parameters<InterviewKitRepository["archive"]>[0]){return this.db.transaction(async tx=>{await tx.execute(sql`select pg_advisory_xact_lock(hashtextextended(${`interview-kit:${i.workspaceId}:${i.kitRef}`},0))`);const current=await head(tx,i.workspaceId,i.kitRef);if(current.revision!==i.expectedRevision)throw new Error("stale_head");const hash=interviewKitHash({payload:current.payload,source:current.source_snapshot,state:"archived"});const inserted=one(rows<any>(await tx.execute(sql`insert into orchestrator_interview_kit_revisions(workspace_id,kit_ref,revision,previous_hash,kit_hash,state,source_id,source_snapshot,payload,created_by_actor_id) values(${i.workspaceId}::uuid,${i.kitRef},${current.revision+1},${current.kit_hash},${hash},'archived',${current.source_id}::uuid,${JSON.stringify(current.source_snapshot)}::jsonb,${JSON.stringify(current.payload)}::jsonb,${i.actorId}::uuid) returning kit_ref,revision,state,payload,source_snapshot`)),"write_conflict");return project(inserted);});}
}
