import { randomUUID } from "node:crypto";
import { existsSync, readFileSync } from "node:fs";
import pg from "pg";
import { drizzle } from "drizzle-orm/node-postgres";
import { DrizzleOperationReadRepository } from "@/connectors/operations/operation-read-drizzle-repository";
import { DrizzlePrimaryResultActionCatalogAdapter } from "@/connectors/operations/primary-result-action-catalog-drizzle-adapter";
import { DrizzlePrimaryResultBindingLifecycleRepository } from "@/connectors/operations/primary-result-binding-lifecycle-drizzle-repository";
import { createPrimaryResultBindingRevision, primaryResultSelector } from "@/domain/operations/primary-result";
import { createSliceRevision } from "@/domain/slices/slice-definition";
import { categoryDefinitionPublicRef, categoryDimensionPublicRef } from "@/domain/categories/public-reference";

if (existsSync(".env.local")) process.loadEnvFile(".env.local");
const connectionString = process.env.DIRECT_DATABASE_URL?.trim() || process.env.DATABASE_URL?.trim();
if (!connectionString) throw new Error("postgres_connection_not_configured");
const client = new pg.Client({ connectionString }), rollback = new Error("operation_read_outer_rollback");
const q = (text: string, values: readonly unknown[] = []) => client.query(text, [...values]);
await client.connect();
try {
  await q("begin");
  // PRE on a fresh database installs inside the outer rollback; an already
  // applied local development database is verified in place without replaying
  // non-idempotent trigger declarations.
  const bindingTables = await q("select to_regclass('public.primary_result_binding_revisions') is not null as present");
  if (bindingTables.rows[0]?.present !== true) await q(readFileSync("drizzle/20260817162000_primary_result_binding_lifecycle.sql", "utf8"));
  const ws=randomUUID(), user=randomUUID(), connection=randomUUID(), source=randomUUID(), account=randomUUID(), campaign=randomUUID(), missingCampaign=randomUUID(), adset=randomUUID(), md=randomUUID(), market=randomUUID(), sd=randomUUID(), segment=randomUUID(), org=randomUUID(), slice=randomUUID(), revisionId=randomUUID(), predicate=randomUUID(), campaignExternal=`campaign_${campaign.slice(0,12)}`, missingCampaignExternal=`campaign_${missingCampaign.slice(0,12)}`, adsetExternal=`adset_${adset.slice(0,12)}`;
  await q("insert into users(id,email) values($1,$2)",[user,`${user}@invalid.local`]); await q("insert into workspaces(id,name) values($1,'operation projection verifier')",[ws]); await q("insert into memberships(workspace_id,user_id,role) values($1,$2,'owner')",[ws,user]);
  await q("insert into meta_connections(id,workspace_id,external_connection_key,display_name,graph_api_version,field_catalog_version) values($1,$2,$3,'fixture','v23.0','fixture')",[connection,ws,`fixture_${connection}`]); await q("insert into data_sources(id,workspace_id,meta_connection_id,platform,external_account_id,display_name) values($1,$2,$3,'meta_ads',$4,'fixture')",[source,ws,connection,`act_${account}`]); await q("insert into ad_accounts(id,workspace_id,data_source_id,external_account_id,name,currency,timezone) values($1,$2,$3,$4,'fixture','TRY','Europe/Istanbul')",[account,ws,source,`act_${account}`]);
  await q("insert into ad_campaigns(id,workspace_id,ad_account_id,external_campaign_id,name,campaign_budget_optimization,daily_budget_minor) values($1,$2,$3,$4,'campaign',false,1000),($5,$2,$3,$6,'missing lead',true,900)",[campaign,ws,account,campaignExternal,missingCampaign,missingCampaignExternal]); await q("insert into meta_ad_sets(id,workspace_id,ad_account_id,campaign_id,external_ad_set_id,name,daily_budget_minor,raw_payload_hash,source_graph_version,field_catalog_version,provenance) values($1,$2,$3,$4,$5,'adset',500,'a','v','v','{}')",[adset,ws,account,campaign,adsetExternal]);
  await q("insert into category_dimensions(id,workspace_id,key,name,cardinality,allowed_entity_levels) values($1,$2,'market','Market','single',array['campaign','ad_set']::category_entity_level[]),($3,$2,'segment','Segment','single',array['campaign','ad_set']::category_entity_level[])",[md,ws,sd]); await q("insert into category_definitions(id,workspace_id,dimension_id,key,label) values($1,$2,$3,'yerli','Yerli'),($4,$2,$5,'a','A')",[market,ws,md,segment,sd]);
  const categoryEvidence = JSON.stringify([{ kind: "fixture", ref: "projection" }]);
  await q("insert into category_assignments(workspace_id,dimension_id,definition_id,entity_level,campaign_id,operation,source,evidence,confidence) values($1,$2,$3,'campaign',$4,'add','manual',$5::jsonb,1),($1,$6,$7,'campaign',$4,'add','manual',$5::jsonb,1),($1,$2,$3,'campaign',$8,'add','manual',$5::jsonb,1),($1,$6,$7,'campaign',$8,'add','manual',$5::jsonb,1)",[ws,md,market,campaign,categoryEvidence,sd,segment,missingCampaign]);
  await q("insert into organization_campaigns(id,workspace_id,label,market_definition_id,created_by_actor_id) values($1,$2,'Kurum',$3,$4)",[org,ws,market,user]); await q("insert into organization_campaign_meta_memberships(workspace_id,organization_campaign_id,campaign_id,market_definition_id,effective_from,assigned_by_actor_id) values($1,$2,$3,$4,now(),$5),($1,$2,$6,$4,now(),$5)",[ws,org,campaign,market,user,missingCampaign]);
  const revision=createSliceRevision({sliceRef:"slice_operation_projection",revisionRef:"slice_revision_operation_projection",revisionNumber:1,market:{dimensionId:categoryDimensionPublicRef("market"),valueId:categoryDefinitionPublicRef("market","yerli"),key:"yerli"},predicates:[{dimensionId:categoryDimensionPublicRef("segment"),key:"segment",values:[{valueId:categoryDefinitionPublicRef("segment","a"),key:"a"}]}]});
  await q("insert into slices(id,workspace_id,slice_ref,label,market_definition_id,created_by_actor_id) values($1,$2,$3,'Scope',$4,$5)",[slice,ws,revision.sliceRef,market,user]); await q("insert into slice_revisions(id,workspace_id,slice_id,slice_ref,revision_number,revision_ref,definition_hash,market_definition_id,lifecycle,created_by_actor_id) values($1,$2,$3,$4,1,$5,$6,$7,'published',$8)",[revisionId,ws,slice,revision.sliceRef,revision.revisionRef,revision.definitionHash,market,user]); await q("update slices set current_published_revision_id=$1 where id=$2",[revisionId,slice]); await q("insert into slice_revision_predicates(id,workspace_id,slice_revision_id,dimension_id,position) values($1,$2,$3,$4,1)",[predicate,ws,revisionId,sd]); await q("insert into slice_revision_predicate_values(workspace_id,predicate_id,definition_id,position) values($1,$2,$3,1)",[ws,predicate,segment]);
  const insight=async(level:"campaign"|"ad_set",external:string,day:string,spend:number,actions:number,attribution="7d_click",currency="TRY",availability="available",actionType="lead")=>{const id=randomUUID();await q("insert into meta_daily_insights(id,workspace_id,meta_connection_id,ad_account_id,entity_level,external_entity_id,date_start,date_stop,attribution_label,currency,timezone,source_revision,source_payload_hash,first_seen_at,last_seen_at) values($1,$2,$3,$4,$5,$6,$7,$7,$8,$9,'Europe/Istanbul','fixture',repeat('a',64),now(),now())",[id,ws,connection,account,level,external,day,attribution,currency]);await q("insert into meta_daily_insight_metrics(daily_insight_id,metric_key,action_type,aggregation,value_decimal,value_minor,currency,provenance,availability,source_revision,source_payload_hash,first_seen_at,last_seen_at) values($1,'spend','','additive',null,$2,$3,'{}',$4::jsonb,'fixture',repeat('b',64),now(),now()),($1,'actions',$6,'additive',$5,null,$3,'{}',$4::jsonb,'fixture',repeat('c',64),now(),now())",[id,spend,currency,JSON.stringify({state:availability}),actions,actionType]);};
  await insight("campaign",campaignExternal,"2026-08-01",100,2);await insight("campaign",campaignExternal,"2026-08-02",200,3);await insight("campaign",missingCampaignExternal,"2026-08-01",10,4,"7d_click","TRY","available","purchase");await insight("campaign",missingCampaignExternal,"2026-08-02",20,5,"7d_click","TRY","available","purchase");await insight("ad_set",adsetExternal,"2026-08-01",40,0);await insight("ad_set",adsetExternal,"2026-08-02",60,0);
  const base=drizzle(client), nested=new Proxy(base,{get(target,key){if(key!=="execute")return Reflect.get(target,key);return async(statement:any)=>{const text=statement?.queryChunks?.flatMap((part:any)=>part?.value??[]).join("").toLowerCase()??"";return text.startsWith("set local transaction")?{rows:[]}:target.execute(statement);};}}), database={transaction:async<T>(work:(tx:any)=>Promise<T>)=>{await q("savepoint operation_projection");try{const out=await work(nested);await q("release savepoint operation_projection");return out;}catch(error){await q("rollback to savepoint operation_projection");await q("release savepoint operation_projection");throw error;}}};
  const catalog=await new DrizzlePrimaryResultActionCatalogAdapter(database as never).load(ws);if(!catalog)throw new Error("catalog_fixture_unavailable");const bindingRepo=new DrizzlePrimaryResultBindingLifecycleRepository(database as never), make=(target:any,createdAt:string,previousRevisionHash?:string)=>createPrimaryResultBindingRevision({bindingId:randomUUID(),workspaceId:ws,target,state:"bound",selector:primaryResultSelector("lead",catalog.catalog),actionCatalog:catalog.catalog,createdAt,previousRevisionHash});const orgBinding=make({kind:"organization_campaign",organizationCampaignId:org},"2026-08-03T00:00:00.000Z"),sliceBinding=make({kind:"slice",sliceId:slice},"2026-08-03T00:01:00.000Z");await bindingRepo.persist({workspaceId:ws,actorId:user,actorRole:"owner",expectedHeadVersion:0,expectedRevisionHash:null,revision:orgBinding,actionCatalog:catalog.catalog});await bindingRepo.persist({workspaceId:ws,actorId:user,actorRole:"owner",expectedHeadVersion:0,expectedRevisionHash:null,revision:sliceBinding,actionCatalog:catalog.catalog});
  const repo=new DrizzleOperationReadRepository(database as never), period={startDate:"2026-08-01",endDate:"2026-08-02"},global=await repo.load({workspaceId:ws,period,sliceRef:null,limit:1,cursor:null}),globalAll=await repo.load({workspaceId:ws,period,sliceRef:null,limit:10,cursor:null}),scoped=await repo.load({workspaceId:ws,period,sliceRef:revision.sliceRef,limit:1,cursor:null}),scopedAllBound=await repo.load({workspaceId:ws,period,sliceRef:revision.sliceRef,limit:10,cursor:null}),next=await repo.load({workspaceId:ws,period,sliceRef:revision.sliceRef,limit:1,cursor:scoped.nextCursor});let crossContextRejected=false;try{await repo.load({workspaceId:ws,period:{startDate:"2026-08-01",endDate:"2026-08-01"},sliceRef:revision.sliceRef,limit:1,cursor:scoped.nextCursor});}catch{crossContextRejected=true;}
  const unbound=createPrimaryResultBindingRevision({bindingId:sliceBinding.bindingId,workspaceId:ws,target:sliceBinding.target,state:"unbound",previousRevisionHash:sliceBinding.revisionHash,createdAt:"2026-08-03T00:02:00.000Z"});await bindingRepo.persist({workspaceId:ws,actorId:user,actorRole:"owner",expectedHeadVersion:1,expectedRevisionHash:sliceBinding.revisionHash,revision:unbound,actionCatalog:null});
  const fallback=await repo.load({workspaceId:ws,period,sliceRef:revision.sliceRef,limit:10,cursor:null}),partial=await repo.load({workspaceId:ws,period:{startDate:"2026-08-01",endDate:"2026-08-03"},sliceRef:revision.sliceRef,limit:10,cursor:null});
  const unavailableCampaign = (loaded: Awaited<ReturnType<typeof repo.load>>, campaignId=campaign) => { const fact=loaded.facts.find(f=>f.campaignId===campaignId && f.adSetId===null); return fact?.primaryResult===null && fact.primaryResultCostMinor===null && fact.primaryResultSource==="unavailable" && fact.reasonCodes.includes("primary_result_unavailable"); };
  const actionMissing=await repo.load({workspaceId:ws,period,sliceRef:revision.sliceRef,limit:10,cursor:null});
  await q("savepoint non_ready"); await q("update meta_daily_insight_metrics m set availability=$1::jsonb from meta_daily_insights i where m.daily_insight_id=i.id and m.metric_key='actions' and i.entity_level='campaign'",[JSON.stringify({state:"unsupported"})]); const nonReady=await repo.load({workspaceId:ws,period,sliceRef:revision.sliceRef,limit:10,cursor:null}); await q("rollback to savepoint non_ready"); await q("release savepoint non_ready");
  await q("savepoint attribution"); await q("update meta_daily_insights set attribution_label='1d_view' where workspace_id=$1 and external_entity_id=$2 and date_start='2026-08-02'",[ws,campaignExternal]); const attributionMismatch=await repo.load({workspaceId:ws,period,sliceRef:revision.sliceRef,limit:10,cursor:null}); await q("rollback to savepoint attribution"); await q("release savepoint attribution");
  await q("savepoint currency"); await q("update meta_daily_insights set currency='USD' where workspace_id=$1 and external_entity_id=$2 and date_start='2026-08-02'",[ws,campaignExternal]); const currencyMismatch=await repo.load({workspaceId:ws,period,sliceRef:revision.sliceRef,limit:10,cursor:null}); await q("rollback to savepoint currency"); await q("release savepoint currency");
  await q("savepoint tamper"); await q("set local session_replication_role='replica'"); await q("update primary_result_binding_revisions set revision_hash=repeat('0',64) where workspace_id=$1 and subject_kind='organization_campaign'",[ws]); let tamperedRejected=false;try{await repo.load({workspaceId:ws,period,sliceRef:revision.sliceRef,limit:10,cursor:null});}catch(error){tamperedRejected=error instanceof Error&&error.message==="operation read rejected: primary_result_binding";}await q("rollback to savepoint tamper"); await q("release savepoint tamper");
  const allScoped=await repo.load({workspaceId:ws,period,sliceRef:revision.sliceRef,limit:10,cursor:null}),campaignFact=scopedAllBound.facts.find(f=>f.campaignId===campaign&&f.adSetId===null),adsetFact=scopedAllBound.facts.find(f=>f.adSetId!==null),globalMain=globalAll.facts.find(f=>f.campaignId===campaign&&f.adSetId===null),scopedMain=scopedAllBound.facts.find(f=>f.campaignId===campaign&&f.adSetId===null);const sufficient=globalMain?.primaryResultSource==="organization_campaign_fallback"&&scopedMain?.primaryResultSource==="slice_binding"&&fallback.facts.every(f=>f.primaryResultSource==="organization_campaign_fallback"||f.primaryResultSource==="unavailable")&&partial.facts.every(f=>f.missingDays.join()==="2026-08-03"&&f.primaryResultSource==="unavailable")&&unavailableCampaign(actionMissing,missingCampaign)&&unavailableCampaign(nonReady)&&unavailableCampaign(attributionMismatch)&&unavailableCampaign(currencyMismatch)&&tamperedRejected&&campaignFact?.spendMinor===300&&campaignFact.primaryResult==="5"&&campaignFact.primaryResultCostMinor==="60"&&adsetFact?.spendMinor===100&&adsetFact.primaryResult==="0"&&adsetFact.primaryResultCostMinor===null&&scoped.nextCursor?.startsWith("operation_cursor_")&&crossContextRejected;if(!sufficient)throw new Error(JSON.stringify({global,scoped,next,fallback,partial,actionMissing,nonReady,attributionMismatch,currencyMismatch,tamperedRejected,crossContextRejected}));throw rollback;
}catch(error){await q("rollback");if(error!==rollback)throw error;const residue=await q("select count(*)::int n from workspaces where name='operation projection verifier'");if(Number(residue.rows[0]?.n)!==0)throw new Error("fixture_residue");console.log(JSON.stringify({ok:true,mode:"pre_unjournaled_outer_rollback",liveEnumSql:true,sliceOverride:true,orgFallback:true,sliceUnboundFallback:true,campaignAndAdSetExactGrain:true,knownZeroCostNull:true,missingActionUnavailable:true,availabilityUnavailable:true,partialDay:true,attributionMismatchUnavailable:true,currencyMismatchUnavailable:true,tamperedBindingRejected:true,cursorV3:true,crossContextRejected:true,writeOperations:0,fixtureWritesRolledBack:true}));}finally{await client.end();}
