import { randomUUID } from "node:crypto";
import pg from "pg";
import { drizzle } from "drizzle-orm/node-postgres";
import { PgDialect } from "drizzle-orm/pg-core";
import * as schema from "@/db/schema";
import { DrizzleOperationReadRepository } from "@/connectors/operations/operation-read-drizzle-repository";
import { createSliceRevision } from "@/domain/slices/slice-definition";
import { categoryDefinitionPublicRef, categoryDimensionPublicRef } from "@/domain/categories/public-reference";

const url=process.env.DIRECT_DATABASE_URL??process.env.DATABASE_URL;if(!url)throw new Error("DATABASE_URL required");const client=new pg.Client({connectionString:url});const ROLLBACK=new Error("operation_read_fixture_rollback");
await client.connect();try { await client.query("begin"); const w=randomUUID(),u=randomUUID(),ds=randomUUID(),a=randomUUID(),c=randomUUID(),s=randomUUID(),md=randomUUID(),yd=randomUUID(),sd=randomUUID(),av=randomUUID(),sl=randomUUID(),r=randomUUID(),p=randomUUID();
  await client.query("insert into users(id,email) values($1,$2)",[u,`${u}@invalid.local`]);await client.query("insert into workspaces(id,name) values($1,'operation verifier')",[w]);await client.query("insert into memberships(workspace_id,user_id,role) values($1,$2,'owner')",[w,u]);await client.query("insert into data_sources(id,workspace_id,platform,external_account_id,display_name) values($1,$2,'meta_ads',$3,'fixture')",[ds,w,`fixture_${ds}`]);await client.query("insert into ad_accounts(id,workspace_id,data_source_id,external_account_id,name,currency,timezone) values($1,$2,$3,$4,'fixture','TRY','Europe/Istanbul')",[a,w,ds,`act_${a}`]);await client.query("insert into ad_campaigns(id,workspace_id,ad_account_id,external_campaign_id,name,campaign_budget_optimization,daily_budget_minor) values($1,$2,$3,$4,'campaign',false,100)",[c,w,a,`campaign_${c}`]);await client.query("insert into meta_ad_sets(id,workspace_id,ad_account_id,campaign_id,external_ad_set_id,name,daily_budget_minor,raw_payload_hash,source_graph_version,field_catalog_version,provenance) values($1,$2,$3,$4,$5,'adset',10,'a','v','v','{}')",[s,w,a,c,`adset_${s}`]);
  await client.query("insert into category_dimensions(id,workspace_id,key,name,cardinality,allowed_entity_levels) values($1,$2,'market','Market','single',array['campaign','ad_set']::category_entity_level[]),($3,$2,'segment','Segment','single',array['campaign','ad_set']::category_entity_level[])",[md,w,sd]);await client.query("insert into category_definitions(id,workspace_id,dimension_id,key,label) values($1,$2,$3,'yerli','Yerli'),($4,$2,$5,'a','A')",[yd,w,md,av,sd]);const e=JSON.stringify([{kind:'fixture',ref:'evidence_fixture'}]);await client.query("insert into category_assignments(workspace_id,dimension_id,definition_id,entity_level,campaign_id,operation,source,evidence,confidence) values($1,$2,$3,'campaign',$4,'add','manual',$5::jsonb,1),($1,$6,$7,'campaign',$4,'add','manual',$5::jsonb,1)",[w,md,yd,c,e,sd,av]);
  const rev=createSliceRevision({sliceRef:'slice_operation_fixture',revisionRef:'slice_revision_operation_fixture',revisionNumber:1,market:{dimensionId:categoryDimensionPublicRef('market'),valueId:categoryDefinitionPublicRef('market','yerli'),key:'yerli'},predicates:[{dimensionId:categoryDimensionPublicRef('segment'),key:'segment',values:[{valueId:categoryDefinitionPublicRef('segment','a'),key:'a'}]}]});await client.query("insert into slices(id,workspace_id,slice_ref,label,market_definition_id,created_by_actor_id) values($1,$2,$3,'fixture',$4,$5)",[sl,w,rev.sliceRef,yd,u]);await client.query("insert into slice_revisions(id,workspace_id,slice_id,slice_ref,revision_number,revision_ref,definition_hash,market_definition_id,lifecycle,created_by_actor_id) values($1,$2,$3,$4,1,$5,$6,$7,'published',$8)",[r,w,sl,rev.sliceRef,rev.revisionRef,rev.definitionHash,yd,u]);await client.query("update slices set current_published_revision_id=$1 where id=$2",[r,sl]);await client.query("insert into slice_revision_predicates(id,workspace_id,slice_revision_id,dimension_id,position) values($1,$2,$3,$4,1)",[p,w,r,sd]);await client.query("insert into slice_revision_predicate_values(workspace_id,predicate_id,definition_id,position) values($1,$2,$3,1)",[w,p,av]);
  const db=drizzle(client,{schema}),dialect=new PgDialect(),repo=new DrizzleOperationReadRepository({transaction:async work=>work({execute:async(q:unknown)=>dialect.sqlToQuery(q as never).sql.toLowerCase().startsWith('set local transaction')?{rows:[]}:db.execute(q as never)} as never)});const scoped=await repo.load({workspaceId:w,period:{startDate:'2026-08-01',endDate:'2026-08-01'},sliceRef:rev.sliceRef,limit:10,cursor:null});if(scoped.facts.length!==2||scoped.facts.find(x=>x.adSetId)?.market!=='yerli')throw new Error('current slice fixture failed');throw ROLLBACK;
}catch(error){await client.query('rollback');if(error!==ROLLBACK)throw error;const residue=await client.query("select count(*)::int count from workspaces where name='operation verifier'");if(Number(residue.rows[0]?.count)!==0)throw new Error('residue');console.log(JSON.stringify({ok:true,scope:'operation_read_fixture_outer_rollback',fixtureWritesRolledBack:true,repositoryMetaWrites:0}));}finally{await client.end();}
