/** Post-apply acceptance: repository writes are always rolled back with the fixture transaction. */
import { createHash, randomUUID } from "node:crypto";
import { existsSync, readFileSync } from "node:fs";
import { drizzle } from "drizzle-orm/node-postgres";
import { Pool, type PoolClient } from "pg";

import { DrizzleDataHealthFindingDevelopmentLogRepository } from "@/connectors/meta/data-health-finding-development-log-drizzle-repository";
import { buildMetaDataHealthReport, type MetaDataHealthAccountEvidence } from "@/domain/meta/data-health";
import { projectMetaDataHealthObservationEvents } from "@/domain/meta/data-health-observation-lifecycle";
import { publicSource } from "@/domain/source/public-source";
import * as schema from "@/db/schema";

if (existsSync(".env.local")) process.loadEnvFile(".env.local");
const connectionString = process.env.DIRECT_DATABASE_URL?.trim() || process.env.DATABASE_URL?.trim();
if (!connectionString) throw new Error("postgres_connection_not_configured");

const pool = new Pool({ connectionString, max: 2, connectionTimeoutMillis: 5_000, statement_timeout: 8_000, query_timeout: 30_000, lock_timeout: 5_000 });
const tables = ["finding_lifecycle_events", "finding_heads", "development_log_events", "development_log_heads"] as const;
const mode = process.env.DATA_HEALTH_LEDGER_VERIFY_MODE ?? "post_apply";
const traceEnabled = process.env.DATA_HEALTH_LEDGER_VERIFY_TRACE === "1";
const verifierStartedAt = Date.now();
function phase(name: string) { if (traceEnabled) console.error(JSON.stringify({ phase: name, elapsedMs: Date.now() - verifierStartedAt })); }
const zero = "0".repeat(64);
const hash = (value: string) => createHash("sha256").update(value).digest("hex");
const workspaceRef = (id: string) => `workspace_${hash(id).slice(0, 24)}`;
const accountRef = (id: string) => `account_${hash(`account:${id}`).slice(0, 24)}`;
const rows = <T>(result: unknown): readonly T[] => result && typeof result === "object" && "rows" in result && Array.isArray(result.rows)
  ? result.rows as readonly T[] : [];
const postgresCode = (error: unknown): string | null => error && typeof error === "object" && "code" in error && typeof error.code === "string" ? error.code : null;
const report = (workspaceId: string, occurredAt: string, healthy: boolean) => {
  const source = (kind: "canonical_meta_mirror" | "canonical_performance" | "derived_trust") => publicSource({ kind,
    state: "ready", observedAt: occurredAt, freshnessAt: occurredAt, freshnessThresholdMinutes: 1_440, reasonCodes: [] });
  const account: MetaDataHealthAccountEvidence = {
    accountRef: accountRef(workspaceId), currency: "TRY",
    sources: { mirror: source("canonical_meta_mirror"), performance: source("canonical_performance"), trust: source("derived_trust") },
    requiredDates: ["2026-08-16"], observedDates: healthy ? ["2026-08-16"] : [],
    requiredFields: ["campaign"], observedFields: ["campaign"],
  };
  return buildMetaDataHealthReport({ workspaceRef: workspaceRef(workspaceId), workspaceCurrency: "TRY", evaluatedAt: occurredAt, accounts: [account] });
};
async function rejected(client: PoolClient, work: () => Promise<unknown>) {
  await client.query("savepoint data_health_ledger_negative");
  try { await work(); await client.query("release savepoint data_health_ledger_negative"); return false; }
  catch { await client.query("rollback to savepoint data_health_ledger_negative"); return true; }
}
async function cleanupCommittedPostApplyFixture(client: PoolClient, workspaceId: string, foreignWorkspaceId: string, userId: string) {
  // The fixture is generated by this verifier only. Cleanup follows the same
  // child-first tombstoning order as the workspace purge adapter, even if the
  // post-apply concurrency assertion itself failed.
  try { await client.query("rollback"); } catch { /* no open transaction */ }
  await client.query("begin");
  await client.query("update workspaces set lifecycle_state='tombstoning' where id=$1", [workspaceId]);
  for (const table of ["development_log_heads", "development_log_events", "finding_heads", "finding_lifecycle_events"] as const) {
    await client.query(`delete from ${table} where workspace_id=$1`, [workspaceId]);
  }
  await client.query("delete from memberships where workspace_id=$1", [workspaceId]);
  await client.query("delete from workspaces where id=$1", [workspaceId]);
  await client.query("delete from workspaces where id=$1", [foreignWorkspaceId]);
  await client.query("delete from users where id=$1", [userId]);
  await client.query("commit");
}

const client = await pool.connect();
phase("pool_connected");
let second: PoolClient | undefined;
const evidence = {
  outerRollback: false, healthyFirstUnchanged: false, repositoryMaterialized: false, exactReplay: false, observed: false, resolved: false, reopened: false,
  triagePreserved: false, tamperRejected: false, staleCasRejected: false, crossTenantRejected: false,
  invalidLifecycleRejected: false, agentObservationRejected: false, inactiveTriageRejected: false,
  preApplyConcurrencySkipped: false, postApplyConcurrencyVerified: false, rlsForced: false, dataApiGrantsRevoked: false,
  noRlsPolicies: false, requiredFkIndexes: false, zeroResidue: false,
};
try {
  phase("catalog_begin");
  const found = await client.query("select relname from pg_class where relnamespace='public'::regnamespace and relname=any($1::text[])", [tables]);
  if (mode === "pre_apply") {
    if (found.rows.length) throw new Error("migration_already_applied");
    await client.query("begin");
    // The PRE verifier is deliberately applying all DDL inside its one outer
    // rollback. On local PostgreSQL this single setup statement can exceed the
    // normal 8s read-query budget; scope the wider timeout to it only.
    await client.query("set local statement_timeout='30s'; set local lock_timeout='5s'");
    await client.query(readFileSync("drizzle/20260817160000_data_health_finding_development_log_ledger.sql", "utf8"));
    await client.query("set local statement_timeout='8s'");
    phase("pre_migration_loaded");
  } else if (mode === "post_apply") {
    if (found.rows.length !== tables.length) throw new Error("migration_not_applied");
    await client.query("begin");
  } else throw new Error("invalid_verify_mode");

  const workspaceId = randomUUID(); const foreignWorkspaceId = randomUUID(); const userId = randomUUID();
  let fixturePrepared = false;
  try {
    const security = (await client.query(`select count(*) filter (where relrowsecurity and relforcerowsecurity)::int as forced
      from pg_class where oid = any(array[${tables.map(table => `'public.${table}'::regclass`).join(",")}])`)).rows[0];
    evidence.rlsForced = Number(security?.forced) === tables.length;
    const apiGrants = await client.query("select count(*)::int as count from information_schema.role_table_grants where table_schema='public' and table_name=any($1::text[]) and grantee in ('anon','authenticated','service_role')", [tables]);
    evidence.dataApiGrantsRevoked = Number(apiGrants.rows[0]?.count) === 0;
    const policies = await client.query("select count(*)::int as count from pg_policies where schemaname='public' and tablename=any($1::text[])", [tables]);
    evidence.noRlsPolicies = Number(policies.rows[0]?.count) === 0;
    const requiredIndexes = ["finding_heads_workspace_event_fk_idx", "development_log_heads_workspace_event_fk_idx", "development_log_events_workspace_finding_event_fk_idx", "development_log_events_workspace_actor_fk_idx"];
    const indexes = await client.query("select indexname from pg_indexes where schemaname='public' and indexname=any($1::text[])", [requiredIndexes]);
    evidence.requiredFkIndexes = indexes.rows.length === requiredIndexes.length;
    await client.query("insert into users(id,email) values($1,$2)", [userId, `data-health-${userId}@example.test`]);
    await client.query("insert into workspaces(id,name) values($1,'data health verifier'),($2,'data health foreign')", [workspaceId, foreignWorkspaceId]);
    await client.query("insert into memberships(workspace_id,user_id,role) values($1,$2,'owner')", [workspaceId, userId]);

    // Bound to the raw outer client; the execution context prevents a nested BEGIN.
    const execution = drizzle(client, { schema });
    const repository = new DrizzleDataHealthFindingDevelopmentLogRepository(execution as never);
    const firstAt = "2026-08-17T12:00:00.000Z";
    const healthyFirst = await repository.materialize({ workspaceId, report: report(workspaceId, firstAt, true), occurredAt: firstAt }, execution as never);
    phase("healthy_first");
    evidence.healthyFirstUnchanged = healthyFirst.outcome === "unchanged" && healthyFirst.eventHashes.length === 0;
    const firstReport = report(workspaceId, firstAt, false);
    const first = await repository.materialize({ workspaceId, report: firstReport, occurredAt: firstAt }, execution as never);
    phase("opened");
    evidence.repositoryMaterialized = first.outcome === "inserted" && first.eventHashes.length === 1;
    const replay = await repository.materialize({ workspaceId, report: firstReport, occurredAt: firstAt }, execution as never);
    evidence.exactReplay = replay.outcome === "unchanged" && replay.eventHashes[0] === first.eventHashes[0];
    const fingerprint = rows<{ fingerprint: string }>(await execution.execute(`select fingerprint from finding_heads where workspace_id='${workspaceId}'::uuid`))[0]?.fingerprint;
    if (!fingerprint) throw new Error("repository_did_not_create_finding_head");
    await repository.triage({ workspaceId, userId, namespace: "meta_data_health", resolutionScope: workspaceRef(workspaceId), fingerprint,
      state: "triaged", occurredAt: "2026-08-17T12:10:00.000Z", payload: { verifier: true } }, execution as never);
    phase("triaged");

    const observedAt = "2026-08-18T12:00:00.000Z";
    const observedRun = await repository.materialize({ workspaceId, report: report(workspaceId, observedAt, false), occurredAt: observedAt }, execution as never);
    phase("observed");
    const observedHead = rows<{ sequence: number; state: string }>(await execution.execute(`select sequence,state from development_log_heads where workspace_id='${workspaceId}'::uuid and fingerprint='${fingerprint}'`))[0];
    evidence.observed = observedRun.outcome === "inserted";
    evidence.triagePreserved = observedHead?.state === "triaged" && Number(observedHead.sequence) === 3;
    const resolvedAt = "2026-08-19T12:00:00.000Z";
    const resolvedRun = await repository.materialize({ workspaceId, report: report(workspaceId, resolvedAt, true), occurredAt: resolvedAt }, execution as never);
    phase("resolved");
    evidence.resolved = resolvedRun.outcome === "inserted" && rows<{ state: string }>(await execution.execute(`select state from finding_heads where workspace_id='${workspaceId}'::uuid and fingerprint='${fingerprint}'`))[0]?.state === "resolved";
    const reopenedAt = "2026-08-20T12:00:00.000Z";
    const reopenedRun = await repository.materialize({ workspaceId, report: report(workspaceId, reopenedAt, false), occurredAt: reopenedAt }, execution as never);
    phase("reopened");
    evidence.reopened = reopenedRun.outcome === "inserted" && rows<{ sequence: number; state: string }>(await execution.execute(`select sequence,state from finding_heads where workspace_id='${workspaceId}'::uuid and fingerprint='${fingerprint}'`))[0]?.state === "open";

    evidence.tamperRejected = await rejected(client, () => client.query("update finding_lifecycle_events set state='resolved' where workspace_id=$1", [workspaceId]));
    phase("tamper_rejected");
    const staleEvents = projectMetaDataHealthObservationEvents({ workspaceRef: workspaceRef(workspaceId), report: report(workspaceId, "2026-08-21T12:00:00.000Z", false), previousHeads: [], occurredAt: "2026-08-21T12:00:00.000Z" });
    evidence.staleCasRejected = await rejected(client, () => repository.append({ workspaceId, events: staleEvents }, execution as never));
    phase("stale_cas_rejected");
    const eventHash = rows<{ event_hash: string }>(await execution.execute(`select event_hash from finding_lifecycle_events where workspace_id='${workspaceId}'::uuid order by sequence limit 1`))[0]?.event_hash;
    if (!eventHash) throw new Error("finding_event_missing");
    evidence.crossTenantRejected = await rejected(client, () => client.query(`insert into development_log_events(workspace_id,namespace,resolution_scope,fingerprint,sequence,finding_event_hash,source_occurrence_hash,category,state,event_type,actor_kind,actor_user_id,previous_event_hash,event_hash,occurred_at,payload) values($1,'meta_data_health',$2,$3,1,$4,$5,'data','proposed','proposed','system',null,$6,$7,now(),'{}'::jsonb)`, [foreignWorkspaceId, workspaceRef(workspaceId), fingerprint, eventHash, hash("foreign-source"), zero, hash("foreign-event")]));
    phase("cross_tenant_rejected");
    const currentHead = rows<{ sequence: number; event_hash: string }>(await execution.execute(`select sequence,event_hash from finding_heads where workspace_id='${workspaceId}'::uuid and fingerprint='${fingerprint}'`))[0];
    if (!currentHead) throw new Error("finding_head_missing");
    const invalidHash = hash("invalid-lifecycle");
    evidence.invalidLifecycleRejected = await rejected(client, async () => {
      await client.query(`insert into finding_lifecycle_events(workspace_id,namespace,resolution_scope,scope_ref,fingerprint,sequence,event_type,state,evidence_hash,previous_event_hash,event_hash,source_occurrence_hash,report_hash,occurred_at) values($1,'meta_data_health',$2,$3,$4,$5,'reopened','open',$6,$7,$8,$9,$10,now())`, [workspaceId, workspaceRef(workspaceId), accountRef(workspaceId), fingerprint, Number(currentHead.sequence) + 1, hash("invalid-evidence"), currentHead.event_hash, invalidHash, hash("invalid-occurrence"), hash("invalid-report")]);
      await client.query("update finding_heads set sequence=$1,event_hash=$2,evidence_hash=$3 where workspace_id=$4 and fingerprint=$5", [Number(currentHead.sequence) + 1, invalidHash, hash("invalid-evidence"), workspaceId, fingerprint]);
    });
    phase("invalid_lifecycle_rejected");
    evidence.agentObservationRejected = await rejected(client, () => client.query(`insert into development_log_events(workspace_id,namespace,resolution_scope,fingerprint,sequence,finding_event_hash,source_occurrence_hash,category,state,event_type,actor_kind,actor_user_id,previous_event_hash,event_hash,occurred_at,payload) values($1,'meta_data_health',$2,$3,99,$4,$5,'data','proposed','observed','agent',null,$6,$7,now(),'{}'::jsonb)`, [workspaceId, workspaceRef(workspaceId), fingerprint, eventHash, hash("agent-observed-source"), zero, hash("agent-observed-event")]));
    phase("agent_observation_rejected");
    evidence.inactiveTriageRejected = await rejected(client, async () => {
      await client.query("update workspaces set lifecycle_state='tombstoning' where id=$1", [workspaceId]);
      await repository.triage({ workspaceId, userId, namespace: "meta_data_health", resolutionScope: workspaceRef(workspaceId), fingerprint,
        state: "closed", occurredAt: "2026-08-20T12:10:00.000Z", payload: { verifier: true } }, execution as never);
    });
    phase("inactive_triage_rejected");
    fixturePrepared = true;
  } finally {
    if (mode === "pre_apply") { await client.query("rollback"); evidence.outerRollback = true; evidence.preApplyConcurrencySkipped = true; }
    else if (fixturePrepared) await client.query("commit");
    else await client.query("rollback");
  }
  phase("fixture_transaction_finished");
  if (mode === "post_apply") {
    // Post-apply only: a committed fixture lets another client contend for the
    // same row. PRE must never present a same-session lock as concurrency.
    try {
      await client.query("begin");
      const locked = rows<{ id: string }>(await client.query("select id from finding_heads where workspace_id=$1 for update", [workspaceId]));
      if (locked.length !== 1) throw new Error("post_apply_fixture_missing");
      second = await pool.connect(); await second.query("set lock_timeout='150ms'");
      try { await second.query("select id from finding_heads where workspace_id=$1 for update", [workspaceId]); throw new Error("post_apply_lock_not_contended"); }
      catch (error) { if (postgresCode(error) !== "55P03") throw error; evidence.postApplyConcurrencyVerified = true; }
    } finally {
      await cleanupCommittedPostApplyFixture(client, workspaceId, foreignWorkspaceId, userId);
    }
  }
  const remaining = await client.query("select (select count(*)::int from users where id=$1) + (select count(*)::int from workspaces where id in ($2,$3)) as count", [userId, workspaceId, foreignWorkspaceId]);
  const liveTables = await client.query("select relname from pg_class where relnamespace='public'::regnamespace and relname=any($1::text[])", [tables]);
  const noFixtureRows = Number(remaining.rows[0]?.count) === 0;
  const expectedSchema = mode === "pre_apply" ? liveTables.rows.length === 0 : liveTables.rows.length === tables.length;
  evidence.zeroResidue = noFixtureRows && expectedSchema;
} finally {
  phase("pool_closing");
  second?.release(); client.release(); await pool.end();
  phase("pool_closed");
}
const passed = evidence.healthyFirstUnchanged && evidence.repositoryMaterialized && evidence.exactReplay && evidence.observed && evidence.resolved && evidence.reopened
  && evidence.triagePreserved && evidence.tamperRejected && evidence.staleCasRejected && evidence.crossTenantRejected && evidence.invalidLifecycleRejected
  && evidence.agentObservationRejected && evidence.inactiveTriageRejected && evidence.rlsForced && evidence.zeroResidue
  && evidence.dataApiGrantsRevoked && evidence.noRlsPolicies && evidence.requiredFkIndexes
  && (mode === "pre_apply" ? evidence.outerRollback && evidence.preApplyConcurrencySkipped && !evidence.postApplyConcurrencyVerified : !evidence.outerRollback && !evidence.preApplyConcurrencySkipped && evidence.postApplyConcurrencyVerified);
if (!passed) throw new Error(`data_health_ledger_verification_failed:${JSON.stringify(evidence)}`);
console.log(JSON.stringify({ ok: true, mode, ...evidence }));
