import { metaPublicReference } from "@/domain/meta/public-reference";
import { organizationCampaignPublicRef } from "@/domain/campaigns/organization-campaign";

export type OperationPeriod = Readonly<{ startDate: string; endDate: string }>;
export type OperationRowFact = Readonly<{
  workspaceId: string; market: "yerli" | "yabanci" | null; accountId: string; accountName: string; campaignId: string; campaignName: string;
  organizationCampaignId: string | null; organizationCampaignName: string | null; adSetId: string | null; adSetName: string | null;
  cbo: boolean | null; campaignBudgetMinor: number | null; adSetBudgetMinor: number | null; spendMinor: number | null;
  observedDays: readonly string[]; missingDays: readonly string[]; reasonCodes: readonly string[];
  primaryResultBinding: Readonly<{ state: "unbound" } | { state: "bound"; actionType: string; bindingRef: string }>;
  primaryResult: number | null; primaryResultCostMinor: number | null;
}>;
export type OperationReadProjection = Readonly<{ version: "operation-read/1.0.0"; period: OperationPeriod; state: "ready" | "partial" | "empty" | "unavailable"; rows: readonly Readonly<{
  market: "yerli" | "yabanci" | "unknown"; accountRef: string; organizationCampaignRef: string | null; organizationCampaignName: string; campaignRef: string; adSetRef: string | null;
  accountName: string; campaignName: string; adSetName: string | null; currentBudgetMinor: number | null; budgetOwner: "campaign" | "ad_set" | "unknown"; budgetOwnerRef: string | null; spendMinor: number | null;
  primaryResultState: "bound" | "unbound"; primaryResult: number | null; primaryResultCostMinor: number | null;
  sourceState: "ready" | "partial" | "empty" | "unavailable"; missingDays: readonly string[]; reasonCodes: readonly string[];
}>[]; budgetOwners: readonly Readonly<{ ref: string; currentBudgetMinor: number }>[]; authority: Readonly<{ canWriteMeta: false; canExecute: false; canApprove: false }> }>;
const UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const day = (value: string) => { if (!/^\d{4}-\d{2}-\d{2}$/.test(value)) return false; const [year, month, date] = value.split("-").map(Number); const parsed = new Date(Date.UTC(year!, month! - 1, date!)); return parsed.getUTCFullYear() === year && parsed.getUTCMonth() === month! - 1 && parsed.getUTCDate() === date; };
const offset = (value: string, days: number) => new Date(new Date(`${value}T00:00:00Z`).valueOf() + days * 86_400_000).toISOString().slice(0, 10);
const calendar = (startDate: string, endDate: string) => Array.from({ length: Math.floor((Date.parse(`${endDate}T00:00:00Z`) - Date.parse(`${startDate}T00:00:00Z`)) / 86_400_000) + 1 }, (_, index) => offset(startDate, index));
function zonedDay(value: Date, timeZone: string) { try { return new Intl.DateTimeFormat("en-CA", { timeZone, year: "numeric", month: "2-digit", day: "2-digit" }).format(value); } catch { throw new Error("operation read rejected: period"); } }
export function operationPeriod(input: Readonly<{ kind?: "today" | "7d" | "30d" | "custom"; startDate?: string; endDate?: string; now?: Date; workspaceTimeZone?: string }> = {}): OperationPeriod {
  if (!input || typeof input !== "object" || Object.keys(input).some((key) => !["kind", "startDate", "endDate", "now", "workspaceTimeZone"].includes(key))) throw new Error("operation read rejected: period");
  const kind = input.kind ?? "7d"; const now = input.now ?? new Date(); if (!(now instanceof Date) || Number.isNaN(now.valueOf()) || !["today", "7d", "30d", "custom"].includes(kind)) throw new Error("operation read rejected: period");
  if (kind === "custom") { if (!input.startDate || !input.endDate || !day(input.startDate) || !day(input.endDate) || input.startDate > input.endDate || calendar(input.startDate, input.endDate).length > 366) throw new Error("operation read rejected: period"); return Object.freeze({ startDate: input.startDate, endDate: input.endDate }); }
  const endDate = zonedDay(now, input.workspaceTimeZone ?? "UTC"); const days = kind === "today" ? 1 : kind === "30d" ? 30 : 7; return Object.freeze({ startDate: offset(endDate, -(days - 1)), endDate });
}
export function buildOperationReadModel(input: Readonly<{ workspaceId: string; period: OperationPeriod; facts: readonly OperationRowFact[]; unavailable?: boolean }>): OperationReadProjection {
  if (!UUID.test(input.workspaceId) || !day(input.period.startDate) || !day(input.period.endDate) || input.period.startDate > input.period.endDate || calendar(input.period.startDate, input.period.endDate).length > 366 || input.facts.length > 20_000 || input.facts.some((fact) => fact.workspaceId !== input.workspaceId || !UUID.test(fact.accountId) || !UUID.test(fact.campaignId) || fact.adSetId !== null && !UUID.test(fact.adSetId))) throw new Error("operation read rejected: tenant");
  if (input.unavailable) return Object.freeze({ version: "operation-read/1.0.0", period: input.period, state: "unavailable", rows: [], budgetOwners: [], authority: Object.freeze({ canWriteMeta: false, canExecute: false, canApprove: false }) });
  const expectedDays = calendar(input.period.startDate, input.period.endDate);
  const rows = input.facts.map((fact) => { const owner = fact.cbo === true ? "campaign" : fact.cbo === false ? "ad_set" : "unknown" as const; const currentBudgetMinor = owner === "campaign" ? fact.campaignBudgetMinor : owner === "ad_set" ? fact.adSetBudgetMinor : null; const budgetOwnerRef = owner === "campaign" ? metaPublicReference("campaign", input.workspaceId, fact.campaignId) : owner === "ad_set" && fact.adSetId ? metaPublicReference("ad_set", input.workspaceId, fact.adSetId) : null; const observed = [...new Set(fact.observedDays)].sort(), missing = [...new Set(fact.missingDays)].sort(); if (observed.some((date) => !expectedDays.includes(date)) || missing.some((date) => !expectedDays.includes(date)) || observed.some((date) => missing.includes(date)) || [...observed, ...missing].sort().join() !== expectedDays.join()) throw new Error("operation read rejected: coverage"); const sourceState = fact.market === null || missing.length ? "partial" : observed.length ? "ready" : "empty"; const bound = fact.primaryResultBinding.state === "bound";
    return Object.freeze({ market: fact.market ?? "unknown", accountRef: metaPublicReference("account", input.workspaceId, fact.accountId), accountName: fact.accountName, organizationCampaignRef: fact.organizationCampaignId ? organizationCampaignPublicRef(input.workspaceId, fact.organizationCampaignId) : null, organizationCampaignName: fact.organizationCampaignName ?? "Kurum Kampanyası atanmadı", campaignRef: metaPublicReference("campaign", input.workspaceId, fact.campaignId), campaignName: fact.campaignName, adSetRef: fact.adSetId ? metaPublicReference("ad_set", input.workspaceId, fact.adSetId) : null, adSetName: fact.adSetName, currentBudgetMinor, budgetOwner: owner, budgetOwnerRef, spendMinor: fact.spendMinor, primaryResultState: bound ? "bound" : "unbound", primaryResult: bound ? fact.primaryResult : null, primaryResultCostMinor: bound ? fact.primaryResultCostMinor : null, sourceState, missingDays: Object.freeze(missing), reasonCodes: Object.freeze([...fact.reasonCodes].sort()) }); }).sort((a, b) => a.market.localeCompare(b.market) || a.accountRef.localeCompare(b.accountRef) || a.campaignRef.localeCompare(b.campaignRef) || (a.adSetRef ?? "").localeCompare(b.adSetRef ?? ""));
  const state = !rows.length ? "empty" : rows.some((row) => row.sourceState !== "ready") ? "partial" : "ready";
  const owners = new Map<string, number>(); for (const row of rows) if (row.budgetOwnerRef && row.currentBudgetMinor !== null) owners.set(row.budgetOwnerRef, row.currentBudgetMinor);
  const budgetOwners = Object.freeze([...owners.entries()].sort(([a], [b]) => a < b ? -1 : a > b ? 1 : 0).map(([ref, currentBudgetMinor]) => Object.freeze({ ref, currentBudgetMinor })));
  return Object.freeze({ version: "operation-read/1.0.0", period: input.period, state, rows: Object.freeze(rows), budgetOwners, authority: Object.freeze({ canWriteMeta: false, canExecute: false, canApprove: false }) });
}
