"use client";
import { useCallback, useEffect, useState } from "react";
import type { AutonomyRuleDraftRequest, AutonomyRuleStudioResult } from "@/application/autonomy-rule-studio-service";
import styles from "./operating-dashboard.module.css";

type State = { status: "loading" } | { status: "error" | "unavailable"; message: string }
  | { status: "ready"; result: AutonomyRuleStudioResult };
const initial = { ruleRef: "", scopeLevel: "workspace", scopeRef: "", mode: "approval_only", effective: "", expires: "",
  killSwitch: false, maxActions: "", sourceGuidanceRefs: "" };

export function AutonomyStudioPanel() {
  const [state, setState] = useState<State>({ status: "loading" }); const [form, setForm] = useState(initial);
  const [saving, setSaving] = useState(false); const [notice, setNotice] = useState<string | null>(null);
  const load = useCallback(async () => { setState({ status: "loading" }); try {
    const response = await fetch("/api/autonomy-rules", { cache: "no-store", credentials: "same-origin", headers: { "X-ReklamZeka-Intent": "autonomy-rules-read" } });
    const payload = await response.json() as AutonomyRuleStudioResult | { error?: { message?: string } };
    if (!response.ok || !("items" in payload)) { setState({ status: response.status === 503 ? "unavailable" : "error", message: "error" in payload ? payload.error?.message ?? "Autonomy Studio okunamadı." : "Autonomy Studio okunamadı." }); return; }
    setState({ status: "ready", result: payload });
  } catch { setState({ status: "error", message: "Autonomy Studio bağlantısı kurulamadı." }); } }, []);
  useEffect(() => { void load(); }, [load]);
  const draft = useCallback(async () => { setSaving(true); setNotice(null); try {
    const scope = form.scopeLevel === "workspace" ? { level: "workspace" } : form.scopeLevel === "action_type" ? { level: "action_type", actionType: form.scopeRef }
      : { level: form.scopeLevel, ref: form.scopeRef };
    const body: AutonomyRuleDraftRequest = { ruleRef: form.ruleRef, scope: scope as AutonomyRuleDraftRequest["scope"], mode: form.mode as AutonomyRuleDraftRequest["mode"],
      effective: new Date(form.effective).toISOString(), expires: form.expires ? new Date(form.expires).toISOString() : null,
      killSwitch: form.killSwitch, maxActions: form.maxActions ? Number(form.maxActions) : null,
      sourceGuidanceRefs: form.sourceGuidanceRefs.split(",").map((item) => item.trim()).filter(Boolean) };
    const response = await fetch("/api/autonomy-rules", { method: "POST", credentials: "same-origin", headers: { "Content-Type": "application/json", "X-ReklamZeka-Intent": "autonomy-rule-create-draft" }, body: JSON.stringify(body) });
    const payload = await response.json() as { error?: { message?: string } };
    if (!response.ok) throw new Error(payload.error?.message ?? "Draft kaydedilemedi.");
    setForm(initial); setNotice("Normalize draft eklendi. Yayınlanmadı ve hiçbir eyleme yetki vermedi."); await load();
  } catch (error) { setNotice(error instanceof Error ? error.message : "Draft kaydedilemedi."); } finally { setSaving(false); } }, [form, load]);
  return <><section className={styles.pageHero}><div><span className={styles.kicker}>AUTONOMY STUDIO · NORMALIZED REGISTRY</span><h1>Otonomi sınırlarını okuyun ve normalize draft hazırlayın.</h1><p>Serbest metin talimat ve guidance ayrı Guidance Registry’de yönetilir. Burada yalnız eylem motorunun anlayacağı kapsam, mod, zaman ve kill switch alanları saklanır.</p></div><span className={styles.readOnlyBadge}>NO PUBLISH · NO META WRITE</span></section>
    {state.status === "loading" ? <section className={`${styles.panel} ${styles.autonomyStudioState}`} role="status">Otonomi sürümleri yükleniyor…</section> : null}
    {state.status === "unavailable" || state.status === "error" ? <section className={`${styles.panel} ${styles.autonomyStudioState}`} role="alert"><strong>{state.status === "unavailable" ? "Kaynak henüz bağlı değil" : "Autonomy Studio okunamadı"}</strong><p>{state.message}</p><button onClick={() => void load()}>Tekrar dene</button></section> : null}
    {state.status === "ready" ? <div className={styles.autonomyStudioGrid}><section className={`${styles.panel} ${styles.autonomyStudioList}`}><header className={styles.panelHeader}><div><span className={styles.kicker}>REVISION FEED</span><h2>{state.result.items.length} sürüm</h2></div><span>Public-safe</span></header>{state.result.items.length === 0 ? <p>Henüz normalize otonomi kuralı yok.</p> : state.result.items.map((item) => <article key={`${item.ruleRef}:${item.revision}`}><header><strong>{item.ruleRef} · r{item.revision}</strong><span data-state={item.state}>{item.state}</span></header><p>{item.scope.level}{"ref" in item.scope ? ` · ${item.scope.ref}` : "actionType" in item.scope ? ` · ${item.scope.actionType}` : ""}</p><dl><div><dt>Mod</dt><dd>{item.mode}</dd></div><div><dt>Kill switch</dt><dd>{item.killSwitch ? "Açık" : "Kapalı"}</dd></div><div><dt>Etkin</dt><dd>{new Date(item.effective).toLocaleString("tr-TR")}</dd></div><div><dt>Provenance</dt><dd>{item.provenance.normalizedByRole} · {item.provenance.sourceGuidanceRefs.length} guidance</dd></div></dl></article>)}</section>
      <section className={`${styles.panel} ${styles.autonomyStudioForm}`}><header><span className={styles.kicker}>NORMALIZED DRAFT</span><h2>Yeni revision taslağı</h2><p>Workspace, kullanıcı, rol ve revision sunucuda belirlenir.</p></header><div><label>Rule ref<input value={form.ruleRef} onChange={(e) => setForm({ ...form, ruleRef: e.target.value })} placeholder="autonomy_campaign_default" /></label><label>Kapsam<select value={form.scopeLevel} onChange={(e) => setForm({ ...form, scopeLevel: e.target.value, scopeRef: "" })}><option value="workspace">Workspace</option><option value="account">Account</option><option value="internal_category">Internal category</option><option value="campaign">Campaign</option><option value="action_type">Action type</option></select></label><label>Kapsam ref / action type<input value={form.scopeRef} disabled={form.scopeLevel === "workspace"} placeholder={form.scopeLevel === "workspace" ? "Sunucu çalışma alanı" : "Public ref"} onChange={(e) => setForm({ ...form, scopeRef: e.target.value })} /></label><label>Mode<select value={form.mode} onChange={(e) => setForm({ ...form, mode: e.target.value, killSwitch: e.target.value === "denied" ? form.killSwitch : false })}><option value="denied">denied</option><option value="approval_only">approval_only</option><option value="policy_limited">policy_limited</option></select></label><label>Effective<input type="datetime-local" value={form.effective} onChange={(e) => setForm({ ...form, effective: e.target.value })} /></label><label>Expires<input type="datetime-local" value={form.expires} onChange={(e) => setForm({ ...form, expires: e.target.value })} /></label><label>Max actions<input type="number" min="1" value={form.maxActions} onChange={(e) => setForm({ ...form, maxActions: e.target.value })} /></label><label>Source guidance refs<input value={form.sourceGuidanceRefs} onChange={(e) => setForm({ ...form, sourceGuidanceRefs: e.target.value })} placeholder="guidance_one, guidance_two" /></label><label className={styles.autonomyKillSwitch}><input type="checkbox" checked={form.killSwitch} disabled={form.mode !== "denied"} onChange={(e) => setForm({ ...form, killSwitch: e.target.checked })} /> Kill switch</label></div><footer><small>Bu işlem publish, disable, approve veya execute etmez.</small><button disabled={saving || !form.ruleRef || form.scopeLevel !== "workspace" && !form.scopeRef || !form.effective} onClick={() => void draft()}>{saving ? "Kaydediliyor…" : "Normalize draft ekle"}</button></footer>{notice ? <p role="status">{notice}</p> : null}</section></div> : null}</>;
}
