"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import styles from "./budget-pool-hierarchy-panel.module.css";

type Node = Readonly<{ poolRef: string; parentPoolRef: string | null; layer: "market" | "service_family" | "targeting" | "entity" | "named"; market: "domestic" | "international"; currency: string; hardCapDecimal: string; effectiveFrom: string; effectiveTo: string }>;
type Snapshot = Readonly<{ contractVersion: "budget-pool-hierarchy-http/1.0.0"; item: Readonly<{ revision: number; hierarchyHash: string; nodes: readonly Node[]; authority: Readonly<{ recommendationOnly: true; canPublish: false; canApprove: false; canExecute: false; canWriteMeta: false; canEnableAutomation: false }> }> | null; authority: Readonly<{ canRead: true; canSaveDraft: boolean }> }>;
const emptyNodes = Object.freeze([] satisfies readonly Node[]);
function object(value: unknown): value is Record<string, unknown> { return Boolean(value) && typeof value === "object" && !Array.isArray(value); }
function validNode(value: unknown): value is Node { return object(value) && typeof value.poolRef === "string" && (value.parentPoolRef === null || typeof value.parentPoolRef === "string") && ["market", "service_family", "targeting", "entity", "named"].includes(String(value.layer)) && ["domestic", "international"].includes(String(value.market)) && typeof value.currency === "string" && typeof value.hardCapDecimal === "string" && typeof value.effectiveFrom === "string" && typeof value.effectiveTo === "string"; }
export function parseBudgetPoolHierarchySnapshot(value: unknown): Snapshot {
  if (!object(value) || value.contractVersion !== "budget-pool-hierarchy-http/1.0.0" || !object(value.authority) || value.authority.canRead !== true || typeof value.authority.canSaveDraft !== "boolean" || !(value.item === null || object(value.item) && Number.isInteger(value.item.revision) && Array.isArray(value.item.nodes) && value.item.nodes.every(validNode) && object(value.item.authority) && value.item.authority.recommendationOnly === true && value.item.authority.canExecute === false && value.item.authority.canWriteMeta === false)) throw new Error("Bütçe havuzu güvenli sözleşmeyi döndürmedi.");
  return value as unknown as Snapshot;
}
function request(method: "GET" | "POST", body?: unknown) { return fetch("/api/budget-pool-hierarchy", { method, credentials: "same-origin", headers: { "x-reklamzeka-intent": method === "GET" ? "budget-pool-hierarchy-read" : "budget-pool-hierarchy-save", ...(method === "POST" ? { "content-type": "application/json" } : {}) }, ...(body === undefined ? {} : { body: JSON.stringify(body) }) }); }
export function BudgetPoolHierarchyPanel() {
  const [snapshot, setSnapshot] = useState<Snapshot | null>(null); const [state, setState] = useState<"loading" | "ready" | "unavailable">("loading"); const [message, setMessage] = useState(""); const [saving, setSaving] = useState(false);
  const [nodesText, setNodesText] = useState(() => JSON.stringify(emptyNodes, null, 2));
  const load = useCallback(async () => { setState("loading"); setMessage(""); try { const response = await request("GET"); if (!response.ok) throw new Error("unavailable"); const next = parseBudgetPoolHierarchySnapshot(await response.json()); setSnapshot(next); setNodesText(JSON.stringify(next.item?.nodes ?? emptyNodes, null, 2)); setState("ready"); } catch { setState("unavailable"); setNodesText(JSON.stringify(emptyNodes, null, 2)); setMessage("Kayıt defteri şu anda oturum veya kaynak nedeniyle okunamıyor. Hiçbir varsayılan havuz kaydedilmedi."); } }, []);
  useEffect(() => { void load(); }, [load]);
  const roots = useMemo(() => snapshot?.item?.nodes.filter((node) => node.parentPoolRef === null) ?? [], [snapshot]);
  const save = useCallback(async () => { let nodes: unknown; try { nodes = JSON.parse(nodesText); } catch { setMessage("Havuz dizisi geçerli JSON değil."); return; } if (!Array.isArray(nodes) || !nodes.every(validNode)) { setMessage("Her havuz satırı eksiksiz ve tanımlı şemada olmalı."); return; } const current = snapshot?.item; setSaving(true); setMessage(""); try { const response = await request("POST", { command: { revision: (current?.revision ?? 0) + 1, previousHierarchyHash: current?.hierarchyHash ?? "GENESIS", idempotencyKey: `budget-pools.r${(current?.revision ?? 0) + 1}`, nodes } }); if (!response.ok) throw new Error("save"); await load(); setMessage("Havuz taslağı immutable revizyon olarak kaydedildi; uygulama yetkisi hâlâ kapalı."); } catch { setMessage("Kayıt reddedildi. Pazar, tavan ve zaman penceresi sınırlarını kontrol edin."); } finally { setSaving(false); } }, [load, nodesText, snapshot]);
  return <section className={styles.panel} aria-label="Bütçe havuzu çalışma alanı"><div className={styles.header}><div><h2 className={styles.title}>Bütçe Havuzları</h2><p className={styles.hint}>Yerli ve yabancı havuzları ayrıdır. Bu ekran yalnız öneri taslağı kaydeder; Meta bütçesi değiştirmez.</p></div><span className={styles.badge}>Recommendation-only</span></div>{roots.length > 0 && <div className={styles.roots}>{roots.map((root) => <div className={styles.root} key={root.poolRef}><strong>{root.market === "domestic" ? "Yerli" : "Yabancı"} kök havuzu</strong><span>{root.hardCapDecimal} {root.currency} · r{snapshot?.item?.revision}</span></div>)}</div>}<div className={styles.editor}><label htmlFor="budget-pool-nodes">Havuz ağacı</label><textarea id="budget-pool-nodes" value={nodesText} onChange={(event) => setNodesText(event.target.value)} spellCheck={false} disabled={state !== "ready" || !snapshot?.authority.canSaveDraft || saving} /></div><div className={styles.actions}><button type="button" onClick={() => void save()} disabled={state !== "ready" || !snapshot?.authority.canSaveDraft || saving}>{saving ? "Kaydediliyor…" : "Yeni taslak revizyonu kaydet"}</button><button type="button" onClick={() => void load()} disabled={saving}>Yenile</button><span className={message.includes("reddedildi") || message.includes("geçerli") ? styles.error : styles.status}>{state === "loading" ? "Yükleniyor…" : message || "Publish, approval, execute ve Meta write kapalı."}</span></div></section>;
}
