"use client";
import { useCallback, useEffect, useState } from "react";
import styles from "./operating-dashboard.module.css";
type Facet = Readonly<{ facet: string; state: "assigned" | "missing" | "conflict" | "not_configured"; values: readonly string[]; evidenceCount: number; reasonCodes: readonly string[] }>;
type Entry = Readonly<{ campaignRef: string; name: string; accountName: string; fetchedAt: string; facets: readonly Facet[]; reviewRequired: boolean; reasonCodes: readonly string[] }>;
type Snapshot = Readonly<{ version: "campaign-classification-review/1.0.0"; entries: readonly Entry[]; summary: Readonly<{ campaigns: number; reviewRequired: number }>; authority: Readonly<{ canAssign: false; canPublish: false; canAuthorizeAction: false; canWriteMeta: false }> }>;
const labels: Record<string, string> = { market: "Pazar", service: "Hizmet", family: "Kampanya ailesi", geo: "Ülke / bölge", audience: "Hedef kitle", platform: "Platform" };
function parse(value: unknown): Snapshot | null { if (!value || typeof value !== "object" || Array.isArray(value)) return null; const v = value as any; if (v.version !== "campaign-classification-review/1.0.0" || !Array.isArray(v.entries) || !v.summary || !v.authority || v.authority.canAssign !== false || v.authority.canPublish !== false || v.authority.canAuthorizeAction !== false || v.authority.canWriteMeta !== false) return null; return v as Snapshot; }
export function CampaignClassificationReviewPanel() { const [state, setState] = useState<"loading" | "ready" | "session_required" | "unavailable">("loading"); const [snapshot, setSnapshot] = useState<Snapshot | null>(null); const refresh = useCallback(async () => { setState("loading"); try { const response = await fetch("/api/campaign-classification-review", { cache: "no-store", credentials: "same-origin", headers: { "x-reklamzeka-intent": "campaign-classification-review-read" } }); const parsed = response.ok ? parse(await response.json()) : null; setSnapshot(parsed); setState(parsed ? "ready" : response.status === 401 || response.status === 403 ? "session_required" : "unavailable"); } catch { setSnapshot(null); setState("unavailable"); } }, []); useEffect(() => { void refresh(); }, [refresh]);
  return <section className={styles.panel}><header><span className={styles.kicker}>CANONICAL REVIEW QUEUE</span><h2>Kampanya künye inceleme kuyruğu</h2><p>Yalnız Meta aynası ve mevcut kategori kayıtları okunur. İsim/creative’den otomatik künye çıkarımı veya atama yapılmaz.</p></header>{state === "loading" ? <p>Kanıt zinciri okunuyor…</p> : state === "session_required" ? <p>İnceleme kuyruğu için önce Decision Room’da yerel oturumu bağlayın.</p> : state === "unavailable" || !snapshot ? <p>Güvenli inceleme kaynağı şu anda kullanılamıyor.</p> : <><p><strong>{snapshot.summary.reviewRequired}</strong> / {snapshot.summary.campaigns} kampanya insan incelemesi bekliyor.</p><div className={styles.campaignGrid}>{snapshot.entries.map((entry) => <article key={entry.campaignRef} className={styles.campaignCard}><header><strong>{entry.name}</strong><small>{entry.accountName} · {entry.reviewRequired ? "İnceleme gerekli" : "Kayıtlı"}</small></header><dl>{entry.facets.map((item) => <div key={item.facet}><dt>{labels[item.facet] ?? item.facet}</dt><dd>{item.state === "assigned" ? item.values.join(", ") : item.state === "conflict" ? `Çelişki: ${item.reasonCodes.join(", ")}` : item.state === "not_configured" ? "Kategori boyutu tanımlı değil" : "Eksik"}<small> · kanıt: {item.evidenceCount}</small></dd></div>)}</dl>{entry.reasonCodes.length ? <small>İnceleme sinyali: {entry.reasonCodes.join(", ")}</small> : null}</article>)}</div><footer><small>Atama yapmak için mevcut Kategori Envanteri / authoring alanını kullanın. Bu kuyruk atama, policy, action veya Meta write üretmez.</small><button type="button" onClick={() => void refresh()}>Yenile</button></footer></>}</section>; }
