"use client";
import { useCallback, useEffect, useState } from "react";
import styles from "./operating-dashboard.module.css";
type Metric = Readonly<{ valueDecimal: string; currency?: string }>;
type Window = Readonly<{ days: 7 | 30; state: "ready" | "partial" | "unavailable"; observedDays: number; missingDays: readonly string[]; freshnessAt: string | null; attribution: string | null; currency: string | null; spend: Metric | null; outcome: Metric | null; cpa: Metric | null; reasonCodes: readonly string[] }>;
type Account = Readonly<{ accountRef: string; name: string; currency: string | null; windows: readonly Window[] }>;
function parse(value: unknown): readonly Account[] | null { if (!value || typeof value !== "object" || Array.isArray(value)) return null; const body = value as Record<string, unknown>; const authority = body.authority as Record<string, unknown> | undefined; if (body.version !== "canonical-performance-read/1.0.0" || !Array.isArray(body.accounts) || !authority || authority.actionAuthority !== "none" || authority.canPublish !== false || authority.canApprove !== false || authority.canExecute !== false || authority.canWriteMeta !== false) return null; const accounts: Account[] = []; for (const candidate of body.accounts) { if (!candidate || typeof candidate !== "object" || Array.isArray(candidate)) return null; const account = candidate as Record<string, unknown>; if (typeof account.accountRef !== "string" || typeof account.name !== "string" || !Array.isArray(account.windows)) return null; const windows: Window[] = []; for (const window of account.windows) { if (!window || typeof window !== "object" || Array.isArray(window)) return null; const item = window as Record<string, unknown>; if (!(item.days === 7 || item.days === 30) || !["ready", "partial", "unavailable"].includes(item.state as string) || !Number.isSafeInteger(item.observedDays) || !Array.isArray(item.missingDays) || !Array.isArray(item.reasonCodes)) return null; windows.push(item as Window); } accounts.push({ accountRef: account.accountRef, name: account.name, currency: typeof account.currency === "string" ? account.currency : null, windows }); } return accounts; }
function number(metric: Metric | null, currency: string | null) { if (!metric) return "—"; const value = Number(metric.valueDecimal); if (!Number.isFinite(value)) return "—"; return metric.currency ?? currency ? new Intl.NumberFormat("tr-TR", { style: "currency", currency: metric.currency ?? currency ?? "TRY", maximumFractionDigits: 2 }).format(value / 100) : metric.valueDecimal; }
export function CanonicalPerformancePanel() { const [state, setState] = useState<"loading" | "ready" | "session_required" | "unavailable">("loading"); const [accounts, setAccounts] = useState<readonly Account[]>([]); const refresh = useCallback(async () => { setState("loading"); try { const response = await fetch("/api/meta/canonical-performance", { cache: "no-store", credentials: "same-origin" }); const source = response.ok ? parse(await response.json()) : null; if (source) { setAccounts(source); setState("ready"); } else { setAccounts([]); setState(response.status === 401 || response.status === 403 ? "session_required" : "unavailable"); } } catch { setAccounts([]); setState("unavailable"); } }, []); useEffect(() => { void refresh(); }, [refresh]); const window = accounts[0]?.windows.find((candidate) => candidate.days === 7) ?? null; const ready = state === "ready" && window?.state === "ready";
  const waiting = state === "loading" ? "Kanonik insight okunuyor" : state === "session_required" ? "Yerel oturum gerekli" : "Kapsam yetersiz";
  return <section className={styles.metricGrid} aria-label="Canlı performans durumu">{ready ? <><article className={styles.metricCard}><div><span>7 günlük harcama</span><em>Canonical ready</em></div><strong>{number(window!.spend, window!.currency)}</strong><footer><span>{accounts[0]!.name} · {window!.observedDays}/7 gün</span></footer></article><article className={styles.metricCard}><div><span>Sonuç · exact lead</span><em>Canonical ready</em></div><strong>{window!.outcome?.valueDecimal ?? "—"}</strong><footer><span>{window!.attribution ?? "Attribution bilinmiyor"}</span></footer></article><article className={styles.metricCard}><div><span>Lead başı maliyet</span><em>Canonical ready</em></div><strong>{number(window!.cpa, window!.currency)}</strong><footer><span>Exact actions:lead · yeterli kapsam</span></footer></article><article className={styles.metricCard}><div><span>Veri kapsamı</span><em>Salt-okunur</em></div><strong>{window!.observedDays}/7</strong><footer><span>{window!.freshnessAt ? `Son kaynak: ${new Date(window!.freshnessAt).toLocaleString("tr-TR")}` : "Freshness bilinmiyor"}</span></footer></article></> : <><article className={styles.metricCard}><div><span>7 günlük harcama</span><em>{waiting}</em></div><strong>—</strong><footer><span>Yalnız canonical kaynak hazır olunca gösterilir.</span></footer></article><article className={styles.metricCard}><div><span>Sonuç</span><em>{waiting}</em></div><strong>—</strong><footer><span>Canlı outcome metriği olmadan CPA gösterilmez.</span></footer></article><article className={styles.metricCard}><div><span>Lead başı maliyet</span><em>{waiting}</em></div><strong>—</strong><footer><span>Karışık para birimi veya eksik günlerde gizlenir.</span></footer></article><article className={styles.metricCard}><div><span>Veri kapsamı</span><em>Salt-okunur</em></div><strong>—</strong><footer><span>Öneri, aksiyon ve Meta write yok.</span></footer></article></>}</section>; }
