"use client";
import { useState } from "react";
import styles from "./naming-template-panel.module.css";

type Template=Readonly<{templateRef:string;revision:number;state:"draft"|"published"|"disabled";revisionHash:string;namingFamily:string;entityLevel:"campaign"|"ad_set";nameRules:readonly unknown[];corroboration:readonly unknown[];proposedAssignments:readonly unknown[]}>;
type Preview=Readonly<{status:"candidate"|"conflict"|"insufficient_evidence";reasonCodes:readonly string[];proposals:readonly Readonly<{dimensionRef:string;definitionRef:string;disposition:"proposed"|"already_manually_locked"}>[];resultHash:string}>;
const REF=/^[a-z][a-z0-9_]{0,31}_[a-f0-9]{20,64}$/,HASH=/^[a-f0-9]{64}$/;
const record=(value:unknown):value is Record<string,unknown>=>Boolean(value)&&typeof value==="object"&&!Array.isArray(value);
function templates(value:unknown):readonly Template[]{if(!record(value)||!Array.isArray(value.items)||value.items.length>1000)throw new Error();return Object.freeze(value.items.map(item=>{if(!record(item)||typeof item.templateRef!=="string"||!/^naming_template_[a-z0-9][a-z0-9_.:-]{0,95}$/.test(item.templateRef)||!Number.isSafeInteger(item.revision)||!(item.state==="draft"||item.state==="published"||item.state==="disabled")||typeof item.revisionHash!=="string"||!HASH.test(item.revisionHash)||typeof item.namingFamily!=="string"||!(item.entityLevel==="campaign"||item.entityLevel==="ad_set")||!Array.isArray(item.nameRules)||!Array.isArray(item.corroboration)||!Array.isArray(item.proposedAssignments))throw new Error();return Object.freeze({templateRef:item.templateRef,revision:item.revision as number,state:item.state,revisionHash:item.revisionHash,namingFamily:item.namingFamily,entityLevel:item.entityLevel,nameRules:item.nameRules,corroboration:item.corroboration,proposedAssignments:item.proposedAssignments});}));}
function preview(value:unknown):Preview{if(!record(value)||!record(value.result))throw new Error();const r=value.result;if(!(r.status==="candidate"||r.status==="conflict"||r.status==="insufficient_evidence")||!Array.isArray(r.reasonCodes)||r.reasonCodes.some(x=>typeof x!=="string")||!Array.isArray(r.proposals)||typeof r.resultHash!=="string"||!HASH.test(r.resultHash))throw new Error();const proposals=r.proposals.map(p=>{if(!record(p)||typeof p.dimensionRef!=="string"||typeof p.definitionRef!=="string"||!(p.disposition==="proposed"||p.disposition==="already_manually_locked"))throw new Error();return Object.freeze({dimensionRef:p.dimensionRef,definitionRef:p.definitionRef,disposition:p.disposition});});return Object.freeze({status:r.status,reasonCodes:Object.freeze(r.reasonCodes as string[]),proposals:Object.freeze(proposals),resultHash:r.resultHash});}
const command=()=>`naming_template_command_${[...crypto.getRandomValues(new Uint8Array(32))].map(x=>x.toString(16).padStart(2,"0")).join("")}`;
export function NamingTemplatePanel(){
  const [accountRef,setAccountRef]=useState("");const [templateRef,setTemplateRef]=useState("naming_template_new");const [family,setFamily]=useState("campaign_structure");const [level,setLevel]=useState<"campaign"|"ad_set">("campaign");const [tokens,setTokens]=useState("");const [objective,setObjective]=useState("");const [dimensionRef,setDimensionRef]=useState("");const [definitionRef,setDefinitionRef]=useState("");const [entityRef,setEntityRef]=useState("");const [items,setItems]=useState<readonly Template[]>([]);const [selected,setSelected]=useState<Template|null>(null);const [result,setResult]=useState<Preview|null>(null);const [status,setStatus]=useState("idle");
  const call=async(intent:string,body?:unknown,url="/api/naming-templates")=>{const response=await fetch(url,{method:body?"POST":"GET",credentials:"same-origin",headers:{"x-reklamzeka-intent":intent,...(body?{"content-type":"application/json"}:{})},body:body?JSON.stringify(body):undefined});if(!response.ok||!response.headers.get("content-type")?.startsWith("application/json"))throw new Error();return response.json() as Promise<unknown>;};
  const load=async()=>{if(!/^account_[a-f0-9]{24}$/.test(accountRef))return setStatus("invalid");setStatus("loading");try{const found=templates(await call("naming-template-list",undefined,`/api/naming-templates?account=${encodeURIComponent(accountRef)}`));setItems(found);setStatus("ready");}catch{setStatus("error");}};
  const payload=(state:"draft"|"published",expectedRevision:number|null)=>({accountRef,templateRef,commandRef:command(),expectedRevision,state,namingFamily:family,entityLevel:level,nameRules:[{source:level==="campaign"?"campaign_name":"ad_set_name",match:"all",tokens:tokens.split(/[ ,]+/).filter(Boolean)}],corroboration:[{kind:"objective",operator:"equals",expected:[objective]}],proposedAssignments:[{dimensionRef,definitionRef}]});
  const save=async(state:"draft"|"published")=>{setStatus("loading");try{const expected=state==="published"?selected?.revision??null:null;const value=await call("naming-template-save",payload(state,expected));if(!record(value)||!record(value.revision))throw new Error();const saved=templates({items:[value.revision]})[0]!;setSelected(saved);setStatus("saved");await load();}catch{setStatus("error");}};
  const runPreview=async()=>{if(!selected||selected.state!=="published"||!REF.test(entityRef))return setStatus("invalid");setStatus("loading");try{setResult(preview(await call("naming-template-preview",{accountRef,templateRef:selected.templateRef,entityRef})));setStatus("ready");}catch{setStatus("error");}};
  return <section className={styles.panel} aria-labelledby="naming-template-title"><header><div><span>KÜNYE ŞABLONU</span><h2 id="naming-template-title">Adlandırma kanıtı ve önizleme</h2><p>Ad yalnızca aday üretir; objective kanıtı zorunludur. Buradan kategori atanmaz ve Meta’ya yazılmaz.</p></div><strong>Salt öneri</strong></header>
    <div className={styles.grid}><label>Hesap public ref<input value={accountRef} onChange={e=>setAccountRef(e.target.value)} /></label><button onClick={load} disabled={status==="loading"}>Şablonları getir</button><label>Şablon ref<input value={templateRef} onChange={e=>setTemplateRef(e.target.value)} /></label><label>Aile<input value={family} onChange={e=>setFamily(e.target.value)} /></label><label>Seviye<select value={level} onChange={e=>setLevel(e.target.value as typeof level)}><option value="campaign">Campaign</option><option value="ad_set">Ad set</option></select></label><label>Ad tokenları<input value={tokens} onChange={e=>setTokens(e.target.value)} /></label><label>Objective kanıtı<input value={objective} onChange={e=>setObjective(e.target.value)} /></label><label>Boyut ref<input value={dimensionRef} onChange={e=>setDimensionRef(e.target.value)} /></label><label>Tanım ref<input value={definitionRef} onChange={e=>setDefinitionRef(e.target.value)} /></label></div>
    <div className={styles.actions}><button onClick={()=>save("draft")} disabled={status==="loading"}>Taslağı kaydet</button><button onClick={()=>save("published")} disabled={status==="loading"||selected?.state!=="draft"}>İnsan yayını oluştur</button></div>
    {items.length?<div className={styles.list}>{items.map(item=><button key={item.templateRef} onClick={()=>{setSelected(item);setTemplateRef(item.templateRef);setFamily(item.namingFamily);setLevel(item.entityLevel);setResult(null);}}><strong>{item.templateRef}</strong><span>r{item.revision} · {item.state}</span></button>)}</div>:null}
    {selected?.state==="published"?<div className={styles.preview}><label>Campaign / ad set public ref<input value={entityRef} onChange={e=>setEntityRef(e.target.value)} /></label><button onClick={runPreview} disabled={status==="loading"}>Önizlemeyi çalıştır</button></div>:null}
    <p role="status" aria-live="polite">{status==="loading"?"Doğrulanıyor…":status==="error"?"Kanonik kanıt okunamadı.":status==="invalid"?"Public ref veya alanlar geçersiz.":status==="saved"?"İmmutable revizyon kaydedildi.":""}</p>
    {result?<div className={styles.comparison}><article><span>ÖNCE</span><strong>Mevcut manuel kilitler korunur</strong><p>Ad, mevcut kategori gerçeği olarak kullanılmaz.</p></article><article><span>SONRA · {result.status}</span><strong>{result.proposals.length?`${result.proposals.length} öneri`:"Atama önerisi yok"}</strong><ul>{result.proposals.map(p=><li key={`${p.dimensionRef}:${p.definitionRef}`}>{p.dimensionRef} → {p.definitionRef} · {p.disposition}</li>)}</ul><p>{result.reasonCodes.join(", ")||"Kanonik kanıtlar uyumlu."}</p></article></div>:null}
  </section>;
}
