import { createHash } from "node:crypto";

import { GUIDE_ACTIONS, type GuideAction, type GuideRevision } from "@/domain/guides/guide-revision";
import { appendGuideRunTransition, appendGuideRunTransitionV12, createGuideRunV12, resolveGuideRunDisposition, verifyAnyGuideRun, type AnyGuideRun, type GuideRunDisposition, type GuideRunTrigger } from "@/domain/guides/guide-run";

/** Schema-free orchestration contract. Every production port must make its writes append-only and idempotent by ref. */
export const GUIDE_RUN_ORCHESTRATION_VERSION = "guide-run-orchestration/1.1.0" as const;
export type GuideRunServerAuthority = Readonly<{ canMutateGuide: false; canApprove: false; canExecute: false; canWriteMeta: false }>;
const CLOSED: GuideRunServerAuthority = Object.freeze({ canMutateGuide: false, canApprove: false, canExecute: false, canWriteMeta: false });
const HASH = /^[a-f0-9]{64}$/; const UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/;
const REF = /^[a-z][a-z0-9]{0,31}_[a-z0-9][a-z0-9_.:-]{0,126}$/; const MAX_MEMBERS = 10_000;

export type FrozenGuideRunMember = Readonly<{ memberRef: string; membershipHash: string }>;
export type FrozenGuideRunScope = Readonly<{ runRef: string; guideRevisionHash: string; sliceRef: string; sliceDefinitionHash: string; sliceSnapshotHash: string; members: readonly FrozenGuideRunMember[] }>;
export type DailyAgentResult = Readonly<{ outcome: "no_change" | "finding"; evidenceHash: string; findingRef: string | null }>;
export type StageableGuideRunCandidate = Readonly<{ version: "candidate/1.1"; entityRef: string; entityLevel: "campaign" | "adset" | "ad"; membershipHash: string; sliceRef: string; market: "yerli" | "yabanci"; typedAction: Record<string, unknown> }>;
export type HolisticGuideRunResult = Readonly<{ outcome: "no_change" | "finding"; dataQuality: "ready" | "missing" | "stale"; recommendationRef: string | null; candidate: Readonly<{ candidateRef: string; candidateHash: string; action: GuideAction; stageable?: StageableGuideRunCandidate }> | null; evidenceHash: string }>;
type MemberArtifact = Readonly<{ member: FrozenGuideRunMember; result: DailyAgentResult | null; failureCode: string | null }>;
type DispositionArtifact = Readonly<{ disposition: GuideRunDisposition; trusted: Readonly<{ dataQuality: "ready" | "missing" | "stale"; evidenceHash: string }>; analysisOutcome: "finding" | "no_change"; guideRevisionHash: string; mode: GuideRevision["mode"]; actionAllowlist: readonly GuideAction[] }>;
export type FindingObservationIntent = Readonly<{ observationRef: string; findingRef: string; evidenceHash: string; fingerprint: string; observationEvidenceHash: string; lifecycle: "observed"; source: "member" | "holistic"; memberRef: string | null; authority: GuideRunServerAuthority }>;
export type DevelopmentLogIntent = Readonly<{ category: "agent_proposed_analysis"; producer: "agent"; state: "proposed"; outcome: "finding" | "no_change"; candidateRef: string | null; recommendationRef: string | null; authority: GuideRunServerAuthority }>;
export type GuideRunArtifact = Readonly<{
  artifactRef: string; runRef: string; kind: "scope_snapshot" | "member_analysis" | "member_failure" | "holistic_analysis" | "disposition" | "finding_observation" | "development_log_intent";
  payload: FrozenGuideRunScope | MemberArtifact | HolisticGuideRunResult | DispositionArtifact | FindingObservationIntent | DevelopmentLogIntent;
  payloadHash: string; occurredAt: string; authority: GuideRunServerAuthority; immutable: true;
}>;

export interface GuideRunStorePort {
  findByIdempotencyKey(input: Readonly<{ workspaceRef: string; idempotencyKey: string }>): Promise<AnyGuideRun | null>;
  insertIfAbsent(run: AnyGuideRun): Promise<AnyGuideRun>;
  compareAndSet(input: Readonly<{ run: AnyGuideRun; expectedHeadHash: string }>): Promise<AnyGuideRun | null>;
  /** Atomic lease/head/epoch fence. Call immediately before every external side effect. */
  fence(input: Readonly<{ runRef: string; expectedHeadHash: string; leaseToken: string; leaseEpoch: number; now: string }>): Promise<AnyGuideRun | null>;
}
export interface GuideRunFrozenScopePort { loadOrFreeze(input: Readonly<{ run: AnyGuideRun; guide: GuideRevision }>): Promise<FrozenGuideRunScope>; }
export interface GuideRunDailyAgentPort { analyze(input: Readonly<{ analysisRef: string; runRef: string; guideRevisionHash: string; sliceSnapshotHash: string; member: FrozenGuideRunMember; authority: GuideRunServerAuthority }>): Promise<DailyAgentResult>; }
export interface GuideRunHolisticAgentPort { synthesize(input: Readonly<{ analysisRef: string; runRef: string; guideRevisionHash: string; sliceSnapshotHash: string; members: readonly MemberArtifact[]; authority: GuideRunServerAuthority }>): Promise<HolisticGuideRunResult>; }
export interface GuideRunTrustedDataHealthPort { resolve(input: Readonly<{ runRef: string; workspaceRef: string; guideRevisionHash: string; sliceRef: string; sliceSnapshotHash: string }>): Promise<Readonly<{ dataQuality: "ready" | "missing" | "stale"; evidenceHash: string }>>; }
export interface GuideRunArtifactPort { list(runRef: string): Promise<readonly GuideRunArtifact[]>; append(artifact: GuideRunArtifact): Promise<void>; }

export class GuideRunOrchestrationError extends Error {
  constructor(readonly code: "invalid_input" | "revision_mismatch" | "scope_mismatch" | "run_conflict" | "lease_lost" | "agent_contract" | "artifact_corrupt" | "data_health_corrupt") { super(`Guide run orchestration rejected: ${code}`); this.name = "GuideRunOrchestrationError"; }
}
function fail(code: GuideRunOrchestrationError["code"]): never { throw new GuideRunOrchestrationError(code); }
function stable(value: unknown): unknown { if (Array.isArray(value)) return value.map(stable); if (value && typeof value === "object") return Object.fromEntries(Object.entries(value as Record<string, unknown>).sort(([a], [b]) => a.localeCompare(b)).map(([k, v]) => [k, stable(v)])); return value; }
function digest(value: unknown): string { return createHash("sha256").update(JSON.stringify(stable(value))).digest("hex"); }
function instant(value: unknown): string { if (typeof value !== "string" || !/^\d{4}-\d\d-\d\dT\d\d:\d\d:\d\d\.\d{3}Z$/.test(value) || new Date(value).toISOString() !== value) fail("invalid_input"); return value; }
function token(value: unknown): string { if (typeof value !== "string" || !UUID.test(value) || value !== value.toLowerCase()) fail("invalid_input"); return value; }
function exact(value: unknown, keys: readonly string[], code: GuideRunOrchestrationError["code"]): Record<string, unknown> { if (!value || typeof value !== "object" || Array.isArray(value) || Object.keys(value).length !== keys.length || Object.keys(value).some((key) => !keys.includes(key))) fail(code); return value as Record<string, unknown>; }
function bounded(value: unknown, depth = 0): void { if (depth > 12) fail("agent_contract"); if (Array.isArray(value)) { if (value.length > MAX_MEMBERS) fail("agent_contract"); value.forEach((item) => bounded(item, depth + 1)); } else if (value && typeof value === "object") { const entries = Object.entries(value); if (entries.length > 32) fail("agent_contract"); entries.forEach(([key, item]) => { if (key.length > 128) fail("agent_contract"); bounded(item, depth + 1); }); } else if (typeof value === "string" && value.length > 10_000) fail("agent_contract"); }
function freeze<T>(value: T): T { if (Array.isArray(value)) value.forEach(freeze); else if (value && typeof value === "object") Object.values(value as Record<string, unknown>).forEach(freeze); return Object.freeze(value); }
function assertRun(run: AnyGuideRun, guide: GuideRevision): void { if (!verifyAnyGuideRun(run)) fail("artifact_corrupt"); if (run.workspaceRef !== guide.workspaceRef || run.guideRef !== guide.guideRef || run.guideRevisionHash !== guide.revisionHash) fail("revision_mismatch"); }
function cloneMember(member: FrozenGuideRunMember): FrozenGuideRunMember { exact(member, ["memberRef", "membershipHash"], "scope_mismatch"); if (!REF.test(member.memberRef) || !HASH.test(member.membershipHash)) fail("scope_mismatch"); return Object.freeze({ memberRef: member.memberRef, membershipHash: member.membershipHash }); }
function scope(run: AnyGuideRun, guide: GuideRevision, value: FrozenGuideRunScope): FrozenGuideRunScope { exact(value, ["runRef", "guideRevisionHash", "sliceRef", "sliceDefinitionHash", "sliceSnapshotHash", "members"], "scope_mismatch"); if (value.runRef !== run.runRef || value.guideRevisionHash !== run.guideRevisionHash || value.sliceRef !== guide.sliceRef || !HASH.test(value.sliceDefinitionHash) || !HASH.test(value.sliceSnapshotHash) || !Array.isArray(value.members) || value.members.length > MAX_MEMBERS) fail("scope_mismatch"); const members = value.members.map(cloneMember).sort((a, b) => a.memberRef.localeCompare(b.memberRef)); if (new Set(members.map((item) => item.memberRef)).size !== members.length || value.sliceSnapshotHash !== digest({ guideRevisionHash: run.guideRevisionHash, sliceRef: guide.sliceRef, sliceDefinitionHash: value.sliceDefinitionHash, members })) fail("scope_mismatch"); return Object.freeze({ runRef: value.runRef, guideRevisionHash: value.guideRevisionHash, sliceRef: value.sliceRef, sliceDefinitionHash: value.sliceDefinitionHash, sliceSnapshotHash: value.sliceSnapshotHash, members: Object.freeze(members) }); }
function daily(value: DailyAgentResult): DailyAgentResult { exact(value, ["outcome", "evidenceHash", "findingRef"], "agent_contract"); bounded(value); if ((value.outcome !== "finding" && value.outcome !== "no_change") || !HASH.test(value.evidenceHash) || (value.outcome === "finding") !== (value.findingRef !== null) || value.findingRef !== null && (!REF.test(value.findingRef) || !value.findingRef.startsWith("finding_"))) fail("agent_contract"); return Object.freeze({ outcome: value.outcome, evidenceHash: value.evidenceHash, findingRef: value.findingRef }); }
function holistic(value: HolisticGuideRunResult, guide: GuideRevision): HolisticGuideRunResult { exact(value, ["outcome", "dataQuality", "recommendationRef", "candidate", "evidenceHash"], "agent_contract"); bounded(value); if ((value.outcome !== "finding" && value.outcome !== "no_change") || !["ready", "missing", "stale"].includes(value.dataQuality) || !HASH.test(value.evidenceHash) || (value.outcome === "finding") !== (value.recommendationRef !== null) || value.recommendationRef !== null && !value.recommendationRef.startsWith("recommendation_") || value.recommendationRef !== null && !REF.test(value.recommendationRef)) fail("agent_contract"); if (value.candidate === null) return Object.freeze({ ...value }); const keys=Object.keys(value.candidate); if (!(["action","candidateHash","candidateRef"].every(k=>keys.includes(k)) && (keys.length===3 || keys.length===4 && keys.includes("stageable")))) fail("agent_contract"); if (value.outcome !== "finding" || !value.candidate.candidateRef.startsWith("candidate_") || !REF.test(value.candidate.candidateRef) || !HASH.test(value.candidate.candidateHash) || !GUIDE_ACTIONS.includes(value.candidate.action) || !guide.actionAllowlist.includes(value.candidate.action) || (guide.mode !== "prepare_human_approval" && guide.mode !== "limited_autonomy")) fail("agent_contract"); const stageable=value.candidate.stageable; if(stageable){ exact(stageable,["version","entityRef","entityLevel","membershipHash","sliceRef","market","typedAction"],"agent_contract"); if(stageable.version!=="candidate/1.1"||!REF.test(stageable.entityRef)||!["campaign","adset","ad"].includes(stageable.entityLevel)||!HASH.test(stageable.membershipHash)||stageable.sliceRef!==guide.sliceRef||stageable.market!==guide.market||!stageable.typedAction||typeof stageable.typedAction!=="object"||Array.isArray(stageable.typedAction)||value.candidate.candidateHash!==digest({candidateRef:value.candidate.candidateRef,action:value.candidate.action,...stageable}))fail("agent_contract"); } return Object.freeze({ ...value, candidate: Object.freeze({ ...value.candidate, ...(stageable?{stageable:Object.freeze({...stageable})}:{}) }) }); }
function health(value: unknown): Readonly<{ dataQuality: "ready" | "missing" | "stale"; evidenceHash: string }> { exact(value, ["dataQuality", "evidenceHash"], "data_health_corrupt"); const output = value as { dataQuality: "ready" | "missing" | "stale"; evidenceHash: string }; if (!(["ready", "missing", "stale"] as const).includes(output.dataQuality) || !HASH.test(output.evidenceHash)) fail("data_health_corrupt"); return Object.freeze({ ...output }); }
function memberArtifact(value: unknown, kind: "member_analysis" | "member_failure"): MemberArtifact { exact(value, ["member", "result", "failureCode"], "artifact_corrupt"); const output = value as MemberArtifact; const member = cloneMember(output.member); if ((kind === "member_analysis") !== (output.result !== null) || (kind === "member_failure") !== (output.failureCode !== null) || output.failureCode !== null && (!/^[a-z0-9][a-z0-9_:-]{0,127}$/.test(output.failureCode) || output.result !== null)) fail("artifact_corrupt"); return Object.freeze({ member, result: output.result === null ? null : daily(output.result), failureCode: output.failureCode }); }
function observation(value: unknown): FindingObservationIntent { exact(value, ["observationRef", "findingRef", "evidenceHash", "fingerprint", "observationEvidenceHash", "lifecycle", "source", "memberRef", "authority"], "artifact_corrupt"); const output = value as FindingObservationIntent; if (!REF.test(output.observationRef) || !output.observationRef.startsWith("finding_observation_") || !REF.test(output.findingRef) || !output.findingRef.startsWith("finding_") || !HASH.test(output.evidenceHash) || !HASH.test(output.fingerprint) || output.fingerprint !== digest({ findingRef: output.findingRef, source: output.source, memberRef: output.memberRef }) || output.observationEvidenceHash !== output.evidenceHash || output.lifecycle !== "observed" || !["member", "holistic"].includes(output.source) || (output.source === "member") !== (typeof output.memberRef === "string") || output.memberRef !== null && !REF.test(output.memberRef) || JSON.stringify(output.authority) !== JSON.stringify(CLOSED)) fail("artifact_corrupt"); return freeze({ ...output, authority: CLOSED }); }
function developmentIntent(value: unknown): DevelopmentLogIntent { exact(value, ["category", "producer", "state", "outcome", "candidateRef", "recommendationRef", "authority"], "artifact_corrupt"); const output = value as DevelopmentLogIntent; if (output.category !== "agent_proposed_analysis" || output.producer !== "agent" || output.state !== "proposed" || !["finding", "no_change"].includes(output.outcome) || output.candidateRef !== null && (!REF.test(output.candidateRef) || !output.candidateRef.startsWith("candidate_")) || output.recommendationRef !== null && (!REF.test(output.recommendationRef) || !output.recommendationRef.startsWith("recommendation_")) || JSON.stringify(output.authority) !== JSON.stringify(CLOSED)) fail("artifact_corrupt"); return freeze({ ...output, authority: CLOSED }); }
function artifactIdentity(kind: GuideRunArtifact["kind"], payload: GuideRunArtifact["payload"]): unknown { return { kind, payload }; }

export class GuideRunOrchestrationService {
  constructor(private readonly store: GuideRunStorePort, private readonly scopes: GuideRunFrozenScopePort, private readonly dailyAgent: GuideRunDailyAgentPort, private readonly holisticAgent: GuideRunHolisticAgentPort, private readonly dataHealth: GuideRunTrustedDataHealthPort, private readonly artifacts: GuideRunArtifactPort) {}
  async fire(input: Readonly<{ guide: GuideRevision; trigger: GuideRunTrigger; occurredAt: string }>): Promise<AnyGuideRun> {
    const created = createGuideRunV12({ workspaceRef: input.guide.workspaceRef, guideRef: input.guide.guideRef, guideRevisionHash: input.guide.revisionHash, trigger: input.trigger, occurredAt: instant(input.occurredAt) });
    const existing = await this.store.findByIdempotencyKey({ workspaceRef: created.workspaceRef, idempotencyKey: created.idempotencyKey });
    if (existing) { assertRun(existing, input.guide); if (existing.idempotencyKey !== created.idempotencyKey || existing.runRef !== created.runRef || JSON.stringify(stable(existing.trigger)) !== JSON.stringify(stable(created.trigger))) fail("run_conflict"); return existing; }
    const inserted = await this.store.insertIfAbsent(created); assertRun(inserted, input.guide); if (inserted.idempotencyKey !== created.idempotencyKey || inserted.runRef !== created.runRef || JSON.stringify(stable(inserted.trigger)) !== JSON.stringify(stable(created.trigger))) fail("run_conflict"); return inserted;
  }
  async claim(run: AnyGuideRun, input: Readonly<{ leaseToken: string; leaseUntil: string; occurredAt: string }>): Promise<AnyGuideRun> { return this.save(this.append(run, { expectedHeadHash: run.headEventHash, toState: "claimed", leaseToken: token(input.leaseToken), leaseUntil: instant(input.leaseUntil), occurredAt: instant(input.occurredAt) }), run.headEventHash); }
  async renew(run: AnyGuideRun, input: Readonly<{ leaseToken: string; leaseUntil: string; occurredAt: string }>): Promise<AnyGuideRun> { if (!["claimed", "scope_frozen", "analyzing", "recorded", "held", "staged", "no_action"].includes(run.state)) fail("invalid_input"); if (run.version !== "guide-run/1.2.0" && ["recorded", "held", "staged", "no_action"].includes(run.state)) fail("invalid_input"); return this.save(this.append(run, { expectedHeadHash: run.headEventHash, toState: run.state as Exclude<AnyGuideRun["state"], "due">, leaseToken: token(input.leaseToken), leaseUntil: instant(input.leaseUntil), occurredAt: instant(input.occurredAt) }), run.headEventHash); }
  async reclaim(run: AnyGuideRun, input: Readonly<{ leaseToken: string; leaseUntil: string; occurredAt: string }>): Promise<AnyGuideRun> { if (!run.lease || Date.parse(instant(input.occurredAt)) < Date.parse(run.lease.expiresAt)) fail("invalid_input"); if (run.state === "claimed") return this.claim(run, input); if (run.version !== "guide-run/1.2.0" || !["scope_frozen", "analyzing", "recorded", "held", "staged", "no_action"].includes(run.state)) fail("invalid_input"); return this.save(this.append(run, { expectedHeadHash: run.headEventHash, toState: run.state as Exclude<AnyGuideRun["state"], "due">, leaseToken: token(input.leaseToken), leaseUntil: instant(input.leaseUntil), occurredAt: instant(input.occurredAt) }), run.headEventHash); }
  async execute(input: Readonly<{ run: AnyGuideRun; guide: GuideRevision; leaseToken: string; occurredAt: string }>): Promise<Readonly<{ run: AnyGuideRun; disposition: GuideRunDisposition; partial: boolean }>> {
    const at = instant(input.occurredAt); const leaseToken = token(input.leaseToken); let run = input.run; assertRun(run, input.guide);
    let records = await this.load(run.runRef, input.guide);
    let frozen = this.find<FrozenGuideRunScope>(records, "scope_snapshot");
    if (!frozen) { await this.fence(run, leaseToken, at); frozen = scope(run, input.guide, await this.scopes.loadOrFreeze({ run, guide: input.guide })); await this.appendArtifact(run, leaseToken, at, "scope_snapshot", frozen, input.guide); records = await this.load(run.runRef, input.guide); }
    frozen = scope(run, input.guide, frozen);
    if (run.state === "claimed") run = await this.transition(run, "scope_frozen", at, leaseToken, "scope_snapshot_frozen");
    if (run.state === "scope_frozen") run = await this.transition(run, "analyzing", at, leaseToken, "member_analysis_started");
    if (run.state === "analyzing") {
      const members: MemberArtifact[] = [];
      for (const member of frozen.members) {
        const ref = this.ref(run, "member_analysis", { sliceSnapshotHash: frozen.sliceSnapshotHash, member }); const known = this.findMember(records, member);
        if (known) members.push(known); else {
          await this.fence(run, leaseToken, at);
          let result: DailyAgentResult; try { result = daily(await this.dailyAgent.analyze({ analysisRef: ref, runRef: run.runRef, guideRevisionHash: run.guideRevisionHash, sliceSnapshotHash: frozen.sliceSnapshotHash, member, authority: CLOSED })); } catch (error) { if (error instanceof GuideRunOrchestrationError && error.code === "agent_contract") throw error; const item = Object.freeze({ member, result: null, failureCode: "daily_agent_failed" }); await this.appendArtifact(run, leaseToken, at, "member_failure", item, input.guide); members.push(item); records = await this.load(run.runRef, input.guide); continue; } const item = Object.freeze({ member, result, failureCode: null }); await this.appendArtifact(run, leaseToken, at, "member_analysis", item, input.guide); if (result.findingRef) await this.appendArtifact(run, leaseToken, at, "finding_observation", this.observation(run, result.findingRef, result.evidenceHash, "member", member.memberRef), input.guide); members.push(item);
          records = await this.load(run.runRef, input.guide);
        }
      }
      const holisticRef = this.ref(run, "holistic_analysis", { sliceSnapshotHash: frozen.sliceSnapshotHash }); let result = this.find<HolisticGuideRunResult>(records, "holistic_analysis");
      if (!result) { await this.fence(run, leaseToken, at); result = holistic(await this.holisticAgent.synthesize({ analysisRef: holisticRef, runRef: run.runRef, guideRevisionHash: run.guideRevisionHash, sliceSnapshotHash: frozen.sliceSnapshotHash, members: Object.freeze(members), authority: CLOSED }), input.guide); await this.appendArtifact(run, leaseToken, at, "holistic_analysis", result, input.guide); await this.appendArtifact(run, leaseToken, at, "development_log_intent", freeze({ category: "agent_proposed_analysis", producer: "agent", state: "proposed", outcome: result.outcome, candidateRef: result.candidate?.candidateRef ?? null, recommendationRef: result.recommendationRef, authority: CLOSED }), input.guide); }
      await this.reconcile(run, input.guide, frozen, records, leaseToken, at); records = await this.load(run.runRef, input.guide);
      run = await this.transition(run, "recorded", at, leaseToken, "analysis_recorded"); records = await this.load(run.runRef, input.guide);
    }
    await this.reconcile(run, input.guide, frozen, records, leaseToken, at); records = await this.load(run.runRef, input.guide);
    const savedDisposition = this.find<DispositionArtifact>(records, "disposition"); if (savedDisposition && (savedDisposition.guideRevisionHash !== run.guideRevisionHash || savedDisposition.mode !== input.guide.mode || JSON.stringify(savedDisposition.actionAllowlist) !== JSON.stringify(input.guide.actionAllowlist))) fail("artifact_corrupt"); let disposition = savedDisposition?.disposition ?? null;
    if (!disposition) {
      const result = this.find<HolisticGuideRunResult>(records, "holistic_analysis"); if (!result) fail("artifact_corrupt"); await this.fence(run, leaseToken, at);
      const trusted = health(await this.dataHealth.resolve({ runRef: run.runRef, workspaceRef: run.workspaceRef, guideRevisionHash: run.guideRevisionHash, sliceRef: frozen.sliceRef, sliceSnapshotHash: frozen.sliceSnapshotHash }));
      if (result.candidate?.stageable && !frozen.members.some((member) => member.memberRef === result.candidate!.stageable!.entityRef && member.membershipHash === result.candidate!.stageable!.membershipHash)) fail("scope_mismatch");
      disposition = resolveGuideRunDisposition({ mode: input.guide.mode, actionAllowlist: input.guide.actionAllowlist, dataQuality: trusted.dataQuality, analysisOutcome: result.outcome, recommendationRef: result.recommendationRef, candidate: result.candidate }); await this.appendArtifact(run, leaseToken, at, "disposition", Object.freeze({ disposition, trusted, analysisOutcome: result.outcome, guideRevisionHash: run.guideRevisionHash, mode: input.guide.mode, actionAllowlist: input.guide.actionAllowlist }), input.guide);
    }
    if (run.state === "recorded") run = await this.transition(run, disposition.state, at, leaseToken, disposition.reason);
    if (run.state === disposition.state) run = await this.transition(run, "completed", at, leaseToken, "run_recorded");
    return Object.freeze({ run, disposition, partial: records.some((record) => record.kind === "member_failure") });
  }
  private async reconcile(run: AnyGuideRun, guide: GuideRevision, frozen: FrozenGuideRunScope, records: readonly GuideRunArtifact[], leaseToken: string, at: string): Promise<void> {
    for (const record of records) if (record.kind === "member_analysis") { const item = memberArtifact(record.payload, "member_analysis"); if (item.result?.findingRef) { const payload = this.observation(run, item.result.findingRef, item.result.evidenceHash, "member", item.member.memberRef); if (!records.some((candidate) => candidate.kind === "finding_observation" && candidate.artifactRef === this.ref(run, "finding_observation", payload))) await this.appendArtifact(run, leaseToken, at, "finding_observation", payload, guide); } }
    const holisticResult = this.find<HolisticGuideRunResult>(records, "holistic_analysis"); if (holisticResult) { const payload = freeze({ category: "agent_proposed_analysis" as const, producer: "agent" as const, state: "proposed" as const, outcome: holisticResult.outcome, candidateRef: holisticResult.candidate?.candidateRef ?? null, recommendationRef: holisticResult.recommendationRef, authority: CLOSED }); if (!records.some((candidate) => candidate.kind === "development_log_intent" && candidate.artifactRef === this.ref(run, "development_log_intent", payload))) await this.appendArtifact(run, leaseToken, at, "development_log_intent", payload, guide); }
  }
  private observation(run: AnyGuideRun, findingRef: string, evidenceHash: string, source: "member" | "holistic", memberRef: string | null): FindingObservationIntent { const fingerprint = digest({ findingRef, source, memberRef }); return freeze({ observationRef: `finding_observation_${digest({ runRef: run.runRef, evidenceHash, fingerprint }).slice(0, 24)}`, findingRef, evidenceHash, fingerprint, observationEvidenceHash: evidenceHash, lifecycle: "observed", source, memberRef, authority: CLOSED }); }
  private append(run: AnyGuideRun, input: Parameters<typeof appendGuideRunTransition>[1]): AnyGuideRun { return run.version === "guide-run/1.2.0" ? appendGuideRunTransitionV12(run, input) : appendGuideRunTransition(run, input); }
  private async transition(run: AnyGuideRun, toState: Parameters<typeof appendGuideRunTransition>[1]["toState"], at: string, leaseToken: string, reasonCode: string): Promise<AnyGuideRun> { await this.fence(run, leaseToken, at); return this.save(this.append(run, { expectedHeadHash: run.headEventHash, toState, occurredAt: at, leaseToken, reasonCode }), run.headEventHash); }
  private async fence(run: AnyGuideRun, leaseToken: string, now: string): Promise<void> { if (!run.lease) fail("lease_lost"); const current = await this.store.fence({ runRef: run.runRef, expectedHeadHash: run.headEventHash, leaseToken, leaseEpoch: run.lease.epoch, now }); if (!current || !verifyAnyGuideRun(current) || current.runRef !== run.runRef || current.headEventHash !== run.headEventHash || current.lease?.token !== leaseToken || current.lease.epoch !== run.lease.epoch) fail("lease_lost"); }
  private async save(run: AnyGuideRun, expectedHeadHash: string): Promise<AnyGuideRun> { const saved = await this.store.compareAndSet({ run, expectedHeadHash }); if (!saved || !verifyAnyGuideRun(saved) || saved.runRef !== run.runRef || saved.headEventHash !== run.headEventHash) fail("run_conflict"); return saved; }
  private ref(run: AnyGuideRun, kind: GuideRunArtifact["kind"], identity: unknown): string { return `guide_run_artifact_${digest({ runRef: run.runRef, ...(artifactIdentity(kind, identity as GuideRunArtifact["payload"]) as Record<string, unknown>) }).slice(0, 24)}`; }
  private async appendArtifact(run: AnyGuideRun, leaseToken: string, at: string, kind: GuideRunArtifact["kind"], payload: GuideRunArtifact["payload"], guide?: GuideRevision, ref = this.ref(run, kind, payload)): Promise<void> {
    await this.fence(run, leaseToken, at);
    const cloned = freeze(structuredClone(payload));
    const canonicalRef = this.ref(run, kind, cloned);
    const artifact = freeze({ artifactRef: canonicalRef, runRef: run.runRef, kind, payload: cloned, payloadHash: digest(cloned), occurredAt: at, authority: CLOSED, immutable: true } as GuideRunArtifact);
    this.decode(artifact, guide);
    try { await this.artifacts.append(artifact); } catch (error) {
      // An append timeout is ambiguous: only an identical immutable record proves success.
      const present = (await this.load(run.runRef)).find((item) => item.artifactRef === ref);
      if (!present || present.payloadHash !== artifact.payloadHash || present.kind !== kind) throw error;
    }
  }
  private async load(runRef: string, guide?: GuideRevision): Promise<readonly GuideRunArtifact[]> { const values = await this.artifacts.list(runRef); if (values.length > MAX_MEMBERS * 3 + 5) fail("artifact_corrupt"); values.forEach((value) => { exact(value, ["artifactRef", "runRef", "kind", "payload", "payloadHash", "occurredAt", "authority", "immutable"], "artifact_corrupt"); bounded(value.payload); if (value.runRef !== runRef || !REF.test(value.artifactRef) || !HASH.test(value.payloadHash) || value.payloadHash !== digest(value.payload) || value.immutable !== true || JSON.stringify(value.authority) !== JSON.stringify(CLOSED) || !["scope_snapshot", "member_analysis", "member_failure", "holistic_analysis", "disposition", "finding_observation", "development_log_intent"].includes(value.kind)) fail("artifact_corrupt"); const decoded = this.decode(value, guide); const expected = `guide_run_artifact_${digest({ runRef, ...(artifactIdentity(value.kind, decoded) as Record<string, unknown>) }).slice(0, 24)}`; if (value.artifactRef !== expected) fail("artifact_corrupt"); }); return freeze(values.map((value) => structuredClone(value))); }
  private decode(value: GuideRunArtifact, guide?: GuideRevision): GuideRunArtifact["payload"] { switch (value.kind) { case "scope_snapshot": { exact(value.payload, ["runRef", "guideRevisionHash", "sliceRef", "sliceDefinitionHash", "sliceSnapshotHash", "members"], "artifact_corrupt"); const p = value.payload as FrozenGuideRunScope; if (p.runRef !== value.runRef || !REF.test(p.sliceRef) || !HASH.test(p.guideRevisionHash) || !HASH.test(p.sliceDefinitionHash) || !HASH.test(p.sliceSnapshotHash) || !Array.isArray(p.members)) fail("artifact_corrupt"); return freeze({ ...p, members: p.members.map(cloneMember) }); } case "member_analysis": return memberArtifact(value.payload, "member_analysis"); case "member_failure": return memberArtifact(value.payload, "member_failure"); case "holistic_analysis": if (!guide) return freeze(structuredClone(value.payload)) as HolisticGuideRunResult; return holistic(value.payload as HolisticGuideRunResult, guide); case "disposition": { exact(value.payload, ["disposition", "trusted", "analysisOutcome", "guideRevisionHash", "mode", "actionAllowlist"], "artifact_corrupt"); const p = value.payload as DispositionArtifact; const trusted = health(p.trusted); if (!HASH.test(p.guideRevisionHash) || !Array.isArray(p.actionAllowlist) || p.actionAllowlist.some((action) => !GUIDE_ACTIONS.includes(action))) fail("artifact_corrupt"); const prior = p.disposition.candidate; const rebuilt = resolveGuideRunDisposition({ mode: p.mode, actionAllowlist: p.actionAllowlist, dataQuality: trusted.dataQuality, analysisOutcome: p.analysisOutcome, recommendationRef: p.disposition.recommendationRef, candidate: prior && { candidateRef: prior.candidateRef, candidateHash: prior.candidateHash, action: prior.action, ...(prior.stageable ? { stageable: prior.stageable } : {}) } }); if (JSON.stringify(rebuilt) !== JSON.stringify(p.disposition)) fail("artifact_corrupt"); return freeze({ ...p, trusted }); } case "finding_observation": return observation(value.payload); case "development_log_intent": return developmentIntent(value.payload); } }
  private find<T>(records: readonly GuideRunArtifact[], kind: GuideRunArtifact["kind"], ref?: string): T | null { const values = records.filter((record) => record.kind === kind && (!ref || record.artifactRef === ref)); if (values.length > 1) fail("artifact_corrupt"); return values[0]?.payload as T ?? null; }
  private findMember(records: readonly GuideRunArtifact[], member: FrozenGuideRunMember): MemberArtifact | null { const values = records.filter((record) => (record.kind === "member_analysis" || record.kind === "member_failure") && (record.payload as MemberArtifact).member?.memberRef === member.memberRef); if (values.length > 1) fail("artifact_corrupt"); return values[0]?.payload as MemberArtifact ?? null; }
}

/** Test-only CAS/fence adapter; production storage must implement the same checks atomically. */
export class InMemoryGuideRunStore implements GuideRunStorePort {
  private readonly runs = new Map<string, AnyGuideRun>();
  async findByIdempotencyKey(input: Readonly<{ workspaceRef: string; idempotencyKey: string }>) { return [...this.runs.values()].find((run) => run.workspaceRef === input.workspaceRef && run.idempotencyKey === input.idempotencyKey) ?? null; }
  async insertIfAbsent(run: AnyGuideRun) { return await this.findByIdempotencyKey({ workspaceRef: run.workspaceRef, idempotencyKey: run.idempotencyKey }) ?? (this.runs.set(run.runRef, run), run); }
  async compareAndSet(input: Readonly<{ run: AnyGuideRun; expectedHeadHash: string }>) { const current = this.runs.get(input.run.runRef); if (!current || current.headEventHash !== input.expectedHeadHash) return null; this.runs.set(input.run.runRef, input.run); return input.run; }
  async fence(input: Readonly<{ runRef: string; expectedHeadHash: string; leaseToken: string; leaseEpoch: number; now: string }>) { const run = this.runs.get(input.runRef); return run && run.headEventHash === input.expectedHeadHash && run.lease?.token === input.leaseToken && run.lease.epoch === input.leaseEpoch && Date.parse(input.now) < Date.parse(run.lease.expiresAt) ? run : null; }
}
