import { createHash, randomBytes } from "node:crypto";
import { CORE_SKILL_MANIFESTS, CLOSED_SKILL_AUTHORITY } from "@/domain/orchestrator/skill-catalog";
import { authorizeWorkspace, type WorkspaceMembership } from "@/security/authorization";
import type { TrustedDecisionRoomPrincipal } from "@/application/decision-room-agent-contract";
export type CatalogItem=Readonly<{kind:"profile"|"playbook";ref:string;revision:number;state:string;title?:string;url?:string|null;freshness?:string}>;
export type SkillCatalogRepository=Readonly<{list(workspaceId:string):Promise<readonly CatalogItem[]>;appendProfile(input:Readonly<{workspaceId:string;actorId:string;pack:unknown}>):Promise<CatalogItem>;appendPlaybook(input:Readonly<{workspaceId:string;actorId:string;title:string;body:string;sourceRef:string}>):Promise<CatalogItem>;tombstone(input:Readonly<{workspaceId:string;actorId:string;ref:string}>):Promise<CatalogItem>}>;
const hash=(v:unknown)=>createHash("sha256").update(JSON.stringify(v)).digest("hex");
export class SkillCatalogService { constructor(private readonly repo:SkillCatalogRepository,private readonly memberships:readonly WorkspaceMembership[]) {}
  async list(p:TrustedDecisionRoomPrincipal){const m=authorizeWorkspace(p.actor,p.workspaceId,"guidance:read",this.memberships);const items=await this.repo.list(p.workspaceId);return Object.freeze({contractVersion:"skill-catalog-ui/1.0.0",activeProfile:items.find(x=>x.kind==="profile")??null,playbooks:items.filter(x=>x.kind==="playbook"),skills:CORE_SKILL_MANIFESTS.map(({ref,name,version,lifecycle,citationRequired,negativeCapabilities})=>({ref,name,version,lifecycle,citationRequired,negativeCapabilities})),authority:{canSelectProfile:m.role!=="viewer",canCreatePlaybookRevision:m.role!=="viewer",canTombstonePlaybook:m.role!=="viewer",...CLOSED_SKILL_AUTHORITY}})}
  async select(p:TrustedDecisionRoomPrincipal,pack:readonly unknown[]){authorizeWorkspace(p.actor,p.workspaceId,"guidance:draft",this.memberships);if(pack.length!==9)throw new Error("invalid_input");return this.repo.appendProfile({workspaceId:p.workspaceId,actorId:p.actor.userId,pack});}
  async create(p:TrustedDecisionRoomPrincipal,x:Readonly<{title:string;body:string;sourceRef:string}>){authorizeWorkspace(p.actor,p.workspaceId,"guidance:draft",this.memberships);if(!x.title.trim()||!x.body.trim()||!/^source_[a-z0-9_.:-]+$/.test(x.sourceRef)||/\b(policy|rule|scope|approve|execute)\b/i.test(x.body))throw new Error("invalid_input");return this.repo.appendPlaybook({...x,workspaceId:p.workspaceId,actorId:p.actor.userId});}
  async tombstone(p:TrustedDecisionRoomPrincipal,ref:string){authorizeWorkspace(p.actor,p.workspaceId,"guidance:draft",this.memberships);return this.repo.tombstone({workspaceId:p.workspaceId,actorId:p.actor.userId,ref});}
}
export const catalogHash=hash; export const newRef=()=>`playbook_${randomBytes(12).toString("hex")}`;
