import { sql } from "drizzle-orm";
import type { NodePgDatabase } from "drizzle-orm/node-postgres";
import type { CampaignClassificationReviewSource } from "@/domain/campaigns/campaign-classification-review";
import type { CategoryAssignment, CategoryDefinition, CategoryDimension, CategoryEntityLevel, CategoryEntityPath } from "@/domain/categories/registry";
import { categoryEntityPublicRef } from "@/domain/categories/public-reference";
import * as schema from "@/db/schema";
type Database = NodePgDatabase<typeof schema>;
const UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
function rows<T>(value: unknown): readonly T[] { if (!value || typeof value !== "object" || !("rows" in value) || !Array.isArray(value.rows)) throw new Error("classification review rejected: corrupt_store"); return value.rows as readonly T[]; }
function text(value: unknown): string { if (typeof value !== "string" || !value.trim()) throw new Error("classification review rejected: corrupt_store"); return value; }
function date(value: unknown): string { if (!(value instanceof Date) || Number.isNaN(value.valueOf())) throw new Error("classification review rejected: corrupt_store"); return value.toISOString(); }
/** Reads only canonical mirror and registry rows within a repeatable-read, read-only transaction. */
export class DrizzleCampaignClassificationReviewRepository {
  constructor(private readonly database: Pick<Database, "transaction">) {}
  async load(workspaceId: string): Promise<CampaignClassificationReviewSource> {
    if (!UUID.test(workspaceId)) throw new Error("classification review rejected: invalid_scope");
    return this.database.transaction(async (tx) => { await tx.execute(sql`set local transaction isolation level repeatable read`); await tx.execute(sql`set local transaction read only`);
      const campaigns = rows<{ id: unknown; name: unknown; account_name: unknown; fetched_at: unknown }>(await tx.execute(sql`select campaign.id::text, campaign.name, account.name as account_name, campaign.fetched_at from ad_campaigns campaign join ad_accounts account on account.id = campaign.ad_account_id and account.workspace_id = campaign.workspace_id where campaign.workspace_id = ${workspaceId}::uuid and campaign.disappeared_at is null order by campaign.name, campaign.id limit 1001`));
      if (campaigns.length > 1000) throw new Error("classification review rejected: capacity_exceeded");
      const dimensions = rows<any>(await tx.execute(sql`select id::text, key, version, cardinality::text, allowed_entity_levels::text[] from category_dimensions where workspace_id = ${workspaceId}::uuid and archived_at is null order by key`)).map((r) => ({ id: text(r.id), workspaceId, key: text(r.key), version: Number(r.version), cardinality: text(r.cardinality) as "single" | "multi", allowedEntityLevels: Object.freeze(r.allowed_entity_levels as CategoryEntityLevel[]), archivedAt: null } satisfies CategoryDimension));
      const definitions = rows<any>(await tx.execute(sql`select id::text, dimension_id::text, key, label, version from category_definitions where workspace_id = ${workspaceId}::uuid and archived_at is null order by dimension_id, key`)).map((r) => ({ id: text(r.id), workspaceId, dimensionId: text(r.dimension_id), key: text(r.key), label: text(r.label), version: Number(r.version), archivedAt: null } satisfies CategoryDefinition));
      const assignments = rows<any>(await tx.execute(sql`select id::text, dimension_id::text, definition_id::text, entity_level::text, case entity_level when 'campaign' then campaign_id::text when 'ad_set' then ad_set_id::text when 'ad' then ad_id::text when 'creative' then creative_id::text end as entity_id, operation::text, source::text, manual_lock, evidence, confidence, version from category_assignments where workspace_id = ${workspaceId}::uuid and archived_at is null order by id`)).map((r) => ({ id: text(r.id), workspaceId, dimensionId: text(r.dimension_id), definitionId: text(r.definition_id), entity: Object.freeze({ level: text(r.entity_level) as CategoryEntityLevel, id: text(r.entity_id) }), operation: text(r.operation) as CategoryAssignment["operation"], source: text(r.source) as CategoryAssignment["source"], manualLock: r.manual_lock === true, evidence: Object.freeze(Array.isArray(r.evidence) ? r.evidence : []), confidence: Number(r.confidence), version: Number(r.version), archivedAt: null } satisfies CategoryAssignment));
      const paths = rows<any>(await tx.execute(sql`select campaign.id::text as campaign_id, ad_set.id::text as ad_set_id, ad.id::text as ad_id, creative.id::text as creative_id from ad_campaigns campaign left join meta_ad_sets ad_set on ad_set.workspace_id = campaign.workspace_id and ad_set.campaign_id = campaign.id and ad_set.disappeared_at is null left join meta_ads ad on ad.workspace_id = campaign.workspace_id and ad.campaign_id = campaign.id and ad.ad_set_id = ad_set.id and ad.disappeared_at is null left join meta_creatives creative on creative.workspace_id = campaign.workspace_id and creative.id = ad.creative_id and creative.disappeared_at is null where campaign.workspace_id = ${workspaceId}::uuid and campaign.disappeared_at is null and (ad.id is not null or ad_set.id is null or not exists (select 1 from meta_ads child where child.workspace_id = ad_set.workspace_id and child.ad_set_id = ad_set.id and child.disappeared_at is null)) order by campaign.id, ad_set.id nulls first, ad.id nulls first limit 10001`));
      if (paths.length > 10000) throw new Error("classification review rejected: capacity_exceeded");
      return Object.freeze({ campaigns: Object.freeze(campaigns.map((r) => {
        const id = text(r.id);
        if (!UUID.test(id)) throw new Error("classification review rejected: corrupt_store");
        return Object.freeze({ id, ref: categoryEntityPublicRef(workspaceId, "campaign", id), name: text(r.name), accountName: text(r.account_name), fetchedAt: date(r.fetched_at) });
      })), dimensions: Object.freeze(dimensions), definitions: Object.freeze(definitions), assignments: Object.freeze(assignments), paths: Object.freeze(paths.map((r) => Object.freeze({ workspaceId, nodes: Object.freeze([{ level: "campaign" as const, id: text(r.campaign_id) }, ...(r.ad_set_id ? [{ level: "ad_set" as const, id: text(r.ad_set_id) }] : []), ...(r.ad_id ? [{ level: "ad" as const, id: text(r.ad_id) }] : []), ...(r.creative_id ? [{ level: "creative" as const, id: text(r.creative_id) }] : [])] satisfies CategoryEntityPath["nodes"])}))) });
    });
  }
}
